"""Integration tests for the ensemble (metamodel) pipeline.

Exercises the full ensemble pipeline end-to-end using the test data subset
(72 participants, 4 diseases, 3 folds, 6/disease/fold, ~118K sequences).
Base models are auto-trained from scratch on the first run; subsequent tests
reuse cached artifacts where possible.

Test coverage
-------------
I1.  End-to-end multiclass (TRAIN all models 1+2+3, all folds)
I2.  End-to-end binary (TRAIN all, Covid19 vs Healthy/Background)
I3.  End-to-end multi-binary (TRAIN all, each disease vs reference)
I4.  LOAD after TRAIN (reuse I1 artifacts)
I5.  Ensemble resume (run, then resume from feature matrices)
I6.  Base model RESUME (partial train, then resume)
I7.  Mixed LOAD/TRAIN (LOAD model1+model3 from I1, TRAIN model2 fresh)
I8.  Retrain specific model (force retrain model1 with I1 artifacts)
I9.  Classification mode mismatch (LOAD multiclass artifacts for binary)
I10. Reference class mismatch (LOAD with different reference_class)
I11. Disease list mismatch (LOAD with different diseases)
I12. Cross-model class mismatch (model1 multiclass + model2 binary)
I13. Ensemble resume config mismatch (resume with changed config)
I14. Model subset (--models 1 2, no model 3)
I15. Fill strategy multiclass (fill_0.5, verify fill artifacts and n_abstained=0)
I16. Binary M2 exclusion (verify M2 excluded, no M2 columns, n_abstained=0)

NOTE: Model 2's internal StratifiedGroupKFold uses 5 splits by default, which
can be too many for the small test data. The fixtures pass glmnet_cv_n_splits=2
via training_params to reduce the number of internal CV splits.

Requirements
------------
- Test data at tests/test_data/ (generated by scripts/data/create_test_data.py)
- numpy, pandas, scikit-learn, glmnet, joblib

Expected runtime
----------------
First run (computes embeddings + trains all base models): ~5-15 minutes
Subsequent runs (cached embeddings + artifacts): ~2-5 minutes

Running
-------
From Mal-ID-Lite root:
    python -m pytest tests/test_ensemble_integration.py -v

    # Specific test:
    python -m pytest tests/test_ensemble_integration.py::test_i01_multiclass_end_to_end -v

    # With custom n_jobs:
    python -m pytest tests/test_ensemble_integration.py -v --n-jobs 2
"""

import json
import logging
import shutil
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import pytest

pytestmark = pytest.mark.integration

PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from test_helpers import (
    TEST_DATA_DIR,
    TEST_DISEASES,
    TEST_FOLD_IDS,
    TEST_RAW_DIR,
    create_test_loader,
)

from malid_lite.training.training_utils import (
    DISEASE_COL,
    PARTICIPANT_COL,
    SPECIMEN_COL,
    aggregate_fold_results,
    get_model_output_dir,
    get_ensemble_output_dir,
    make_pair_name,
    read_model_summary,
    resolve_model_artifact_dir,
    validate_mode_and_classes,
    validate_model_summary,
)
from malid_lite.training.train_ensemble import (
    TRAINING_CONTEXT,
    auto_train_base_model,
    build_feature_matrix,
    evaluate_predictions,
    resolve_base_model_mode,
    run_ensemble_fold,
    save_fold_artifacts,
    train_ensemble,
    train_metamodel,
    _validate_cross_model_disease_classes,
)


# ---------------------------------------------------------------------------
# Pytest configuration
# ---------------------------------------------------------------------------

def pytest_addoption(parser):
    """Add --n-jobs CLI option for integration tests."""
    parser.addoption(
        "--n-jobs", type=int, default=4,
        help="Parallel workers for Model 2/3 predictions. Default: 4.",
    )


@pytest.fixture(scope="session")
def n_jobs(request):
    """Number of parallel workers from CLI --n-jobs."""
    return request.config.getoption("--n-jobs", default=4)


# ---------------------------------------------------------------------------
# Constants and paths
# ---------------------------------------------------------------------------

# Model 2's internal StratifiedGroupKFold requires n_splits <= min groups per class.
# The test data (72 participants, 4 classes, 3 folds) yields ~5-6 participants per
# class in train_smaller1 (ensemble context), so we reduce from default 5 to 2.
M2_CV_N_SPLITS = 2

# Metamodel's StratifiedGroupKFold also needs n_splits <= min groups per class.
# Validation set in ensemble context has ~2 participants per class, so use 2.
METAMODEL_CV_N_SPLITS = 2

OUTPUT_BASE = Path(__file__).parent / "test_outputs" / "test_ensemble_integration"
TEST_DATASET_NAME = "test-data"
METADATA_PATH = TEST_DATA_DIR / "metadata.tsv"
REFERENCE_CLASS = "Healthy/Background"

# Diseases available in test data (excluding reference)
NON_REF_DISEASES = sorted(d for d in TEST_DISEASES if d != REFERENCE_CLASS)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def loader():
    """Create a test data loader (session-scoped, created once)."""
    return create_test_loader(verbose=0)


@pytest.fixture(scope="session")
def multiclass_base_models(loader, n_jobs) -> Dict:
    """Train all 3 base models for multiclass on test data.

    Session-scoped: trains once, reused across all tests.
    Returns dict with model_dirs, model_summaries, output_base.
    """
    output_base = OUTPUT_BASE / "base_models_multiclass"
    model_dirs = {}
    model_summaries = {}

    for model_num in [1, 2, 3]:
        model_out = output_base / f"model{model_num}"

        # Check if already trained (summary exists)
        summary_files = list(model_out.glob("summary_*.json")) if model_out.exists() else []
        if summary_files:
            summary = read_model_summary(model_out)
            if summary is not None:
                model_dirs[model_num] = model_out
                model_summaries[model_num] = summary
                continue

        # Train from scratch
        model_out.mkdir(parents=True, exist_ok=True)

        # Per-model kwargs
        training_params = {}
        extra_kwargs = {}
        if model_num == 2:
            training_params["glmnet_cv_n_splits"] = M2_CV_N_SPLITS
        if model_num == 3:
            embedding_dir = TEST_DATA_DIR / "embeddings"
            extra_kwargs = dict(
                embedding_dir=embedding_dir,
                no_cache_embeddings=False,
                device="cpu",
            )

        auto_train_base_model(
            model_num=model_num,
            training_params=training_params,
            output_dir=model_out,
            metadata_path=METADATA_PATH,
            dataset_name=TEST_DATASET_NAME,
            classification_mode="multiclass",
            reference_class=None,
            diseases=None,
            gene_locus="TCR",
            fold_ids=TEST_FOLD_IDS,
            data_dir=TEST_RAW_DIR,
            cache_dir=TEST_DATA_DIR,
            gene_reference_path=None,
            n_jobs=n_jobs,
            verbose=0,
            resume=False,
            **extra_kwargs,
        )

        model_dirs[model_num] = model_out
        model_summaries[model_num] = read_model_summary(model_out)

    return {
        "model_dirs": model_dirs,
        "model_summaries": model_summaries,
        "output_base": output_base,
    }


@pytest.fixture(scope="session")
def binary_base_models(loader, n_jobs) -> Dict:
    """Train all 3 base models for binary (Covid19 vs Healthy/Background).

    Session-scoped: trains once, reused across binary tests.
    """
    output_base = OUTPUT_BASE / "base_models_binary"
    disease = "Covid19"
    pair_name = make_pair_name(disease, REFERENCE_CLASS)
    model_dirs = {}
    model_summaries = {}

    for model_num in [1, 2, 3]:
        model_out = output_base / f"model{model_num}"
        pair_dir = model_out / pair_name

        # Check if already trained
        summary_files = list(model_out.glob("summary_*.json")) if model_out.exists() else []
        if summary_files and pair_dir.exists():
            summary = read_model_summary(model_out)
            if summary is not None:
                model_dirs[model_num] = pair_dir
                model_summaries[model_num] = summary
                continue

        model_out.mkdir(parents=True, exist_ok=True)

        # Per-model kwargs
        training_params = {}
        extra_kwargs = {}
        if model_num == 2:
            training_params["glmnet_cv_n_splits"] = M2_CV_N_SPLITS
        if model_num == 3:
            embedding_dir = TEST_DATA_DIR / "embeddings"
            extra_kwargs = dict(
                embedding_dir=embedding_dir,
                no_cache_embeddings=False,
                device="cpu",
            )

        auto_train_base_model(
            model_num=model_num,
            training_params=training_params,
            output_dir=model_out,
            metadata_path=METADATA_PATH,
            dataset_name=TEST_DATASET_NAME,
            classification_mode="binary",
            reference_class=REFERENCE_CLASS,
            diseases=[disease],
            gene_locus="TCR",
            fold_ids=TEST_FOLD_IDS,
            data_dir=TEST_RAW_DIR,
            cache_dir=TEST_DATA_DIR,
            gene_reference_path=None,
            n_jobs=n_jobs,
            verbose=0,
            resume=False,
            **extra_kwargs,
        )

        model_dirs[model_num] = pair_dir
        model_summaries[model_num] = read_model_summary(model_out)

    return {
        "model_dirs": model_dirs,
        "model_summaries": model_summaries,
        "output_base": output_base,
        "disease": disease,
        "pair_name": pair_name,
    }


# ---------------------------------------------------------------------------
# I1: End-to-end multiclass
# ---------------------------------------------------------------------------

def test_i01_multiclass_end_to_end(loader, multiclass_base_models, n_jobs):
    """I1: End-to-end multiclass ensemble with all 3 base models, all folds."""
    model_dirs = multiclass_base_models["model_dirs"]
    model_summaries = multiclass_base_models["model_summaries"]

    output_dir = OUTPUT_BASE / "ensemble_multiclass"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": TEST_FOLD_IDS,
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=TEST_FOLD_IDS,
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        disease_filter=None,
        reference_class=None,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    # --- Verify fold results ---
    assert len(fold_results) == len(TEST_FOLD_IDS)
    for fr in fold_results:
        assert "ensemble_metrics" in fr
        assert "base_model_metrics" in fr
        em = fr["ensemble_metrics"]
        assert 0.0 <= em["accuracy"] <= 1.0
        assert em["mcc"] is not None
        for num in [1, 2, 3]:
            assert num in fr["base_model_metrics"]

    # --- Verify artifacts on disk ---
    assert (output_dir / "run_config.json").exists()
    assert (output_dir / "ensemble_predictions.csv").exists()
    preds_df = pd.read_csv(output_dir / "ensemble_predictions.csv")
    assert len(preds_df) > 0
    assert "specimen_label" in preds_df.columns
    assert "true_disease" in preds_df.columns
    assert "ensemble_predicted" in preds_df.columns

    for fid in TEST_FOLD_IDS:
        assert (output_dir / f"fold_{fid}_ridge_cv_metamodel.joblib").exists()
        assert (output_dir / f"fold_{fid}_metamodel_config.json").exists()
        assert (output_dir / f"fold_{fid}_ensemble_results.json").exists()

    summary_files = list(output_dir.glob("summary_*.json"))
    assert len(summary_files) == 1
    md_files = list(output_dir.glob("RESULTS_*.md"))
    assert len(md_files) == 1

    # --- Verify summary structure ---
    assert "ensemble" in summary
    assert "base_models" in summary
    ens = summary["ensemble"]
    assert "accuracy_global" in ens
    assert ens["accuracy_global"] > 0
    for num in [1, 2, 3]:
        assert f"model{num}" in summary["base_models"]

    # --- Verify RESULTS MD ---
    md_text = md_files[0].read_text()
    assert "Ensemble Training Results" in md_text
    assert "Model Comparison" in md_text


# ---------------------------------------------------------------------------
# I2: End-to-end binary
# ---------------------------------------------------------------------------

def test_i02_binary_end_to_end(loader, binary_base_models, n_jobs):
    """I2: End-to-end binary ensemble (Covid19 vs Healthy/Background)."""
    model_dirs = binary_base_models["model_dirs"]
    model_summaries = binary_base_models["model_summaries"]
    disease = binary_base_models["disease"]
    disease_filter = (disease, REFERENCE_CLASS)

    output_dir = OUTPUT_BASE / "ensemble_binary" / binary_base_models["pair_name"]
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "binary",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": TEST_FOLD_IDS,
        "disease_filter": list(disease_filter),
        "reference_class": REFERENCE_CLASS,
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=TEST_FOLD_IDS,
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        disease_filter=disease_filter,
        reference_class=REFERENCE_CLASS,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    # --- Verify binary metrics ---
    assert len(fold_results) == len(TEST_FOLD_IDS)
    ens = summary["ensemble"]
    assert "auroc_pooled" in ens
    assert ens["auroc_pooled"] is not None
    assert "mcc" in ens

    # --- Verify binary artifacts ---
    md_files = list(output_dir.glob("RESULTS_*.md"))
    assert len(md_files) == 1
    md_text = md_files[0].read_text()
    assert "AUROC (pooled)" in md_text
    assert "AUROC OvO" not in md_text


# ---------------------------------------------------------------------------
# I3: End-to-end multi-binary
# ---------------------------------------------------------------------------

def test_i03_multi_binary_end_to_end(loader, binary_base_models, n_jobs):
    """I3: Multi-binary ensemble — train one pair, verify cross-pair structure.

    Uses the binary base models (Covid19 vs Healthy/Background) for one pair.
    Verifies the per-pair output structure and summary format.
    """
    from malid_lite.training.train_ensemble import _save_multi_binary_summary

    model_dirs = binary_base_models["model_dirs"]
    model_summaries = binary_base_models["model_summaries"]
    disease = binary_base_models["disease"]
    pair_name = binary_base_models["pair_name"]
    disease_filter = (disease, REFERENCE_CLASS)

    base_output_dir = OUTPUT_BASE / "ensemble_multi_binary"
    pair_output_dir = base_output_dir / pair_name
    if pair_output_dir.exists():
        shutil.rmtree(pair_output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multi-binary",
        "gene_locus": "TCR",
        "models_included": [1, 3],
        "fold_ids": TEST_FOLD_IDS,
        "disease_filter": list(disease_filter),
        "reference_class": REFERENCE_CLASS,
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=TEST_FOLD_IDS,
        model_nums=[1, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=pair_output_dir,
        embedding_dir=embedding_dir,
        disease_filter=disease_filter,
        reference_class=REFERENCE_CLASS,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    assert len(fold_results) == len(TEST_FOLD_IDS)
    assert "auroc_pooled" in summary["ensemble"]

    # --- Save cross-pair summary (single pair in this test) ---
    pairs_to_train = [(disease, REFERENCE_CLASS)]
    all_pair_summaries = {pair_name: summary}
    all_pair_fold_results = {pair_name: fold_results}

    _save_multi_binary_summary(
        base_output_dir, all_pair_summaries, all_pair_fold_results,
        pairs_to_train, REFERENCE_CLASS,
    )

    mb_json_files = list(base_output_dir.glob("multi_binary_summary_*.json"))
    assert len(mb_json_files) >= 1
    with open(mb_json_files[0]) as f:
        cross_json = json.load(f)
    assert cross_json["n_pairs"] == 1
    assert pair_name in cross_json["pairs"]


# ---------------------------------------------------------------------------
# I4: LOAD after TRAIN
# ---------------------------------------------------------------------------

def test_i04_load_after_train(loader, multiclass_base_models, n_jobs):
    """I4: Load pre-trained base models and run ensemble (no retraining)."""
    model_dirs = multiclass_base_models["model_dirs"]
    model_summaries = multiclass_base_models["model_summaries"]

    # Verify all summaries exist (confirming LOAD mode would work)
    for num in [1, 3]:
        assert model_summaries[num] is not None, f"Model {num} summary is None"

    output_dir = OUTPUT_BASE / "ensemble_load_after_train"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 3],
        "fold_ids": [TEST_FOLD_IDS[0]],
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    # Run on just fold 0 for speed
    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    assert len(fold_results) == 1
    assert summary["ensemble"]["accuracy_global"] > 0


# ---------------------------------------------------------------------------
# I5: Ensemble resume
# ---------------------------------------------------------------------------

def test_i05_ensemble_resume(loader, multiclass_base_models, n_jobs):
    """I5: Original run then resume — metrics must match exactly."""
    model_dirs = multiclass_base_models["model_dirs"]
    model_summaries = multiclass_base_models["model_summaries"]

    output_dir = OUTPUT_BASE / "ensemble_resume_test"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    fold_ids = [TEST_FOLD_IDS[0]]
    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": fold_ids,
    }
    embedding_dir = TEST_DATA_DIR / "embeddings"

    # --- Original run ---
    _, original_summary = train_ensemble(
        loader=loader,
        fold_ids=fold_ids,
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    # --- Resume run ---
    _, resume_summary = train_ensemble(
        loader=loader,
        fold_ids=fold_ids,
        model_nums=[1, 2, 3],
        model_dirs={},
        gene_locus="TCR",
        output_dir=output_dir,
        resume=True,
        run_config={**run_config, "resume": True},
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    # --- Compare metrics ---
    orig_ens = original_summary["ensemble"]
    resu_ens = resume_summary["ensemble"]
    assert abs(orig_ens["accuracy_global"] - resu_ens["accuracy_global"]) < 1e-10

    for num in [1, 2, 3]:
        orig_bm = original_summary["base_models"][f"model{num}"]
        resu_bm = resume_summary["base_models"][f"model{num}"]
        assert abs(orig_bm["accuracy_global"] - resu_bm["accuracy_global"]) < 1e-10


# ---------------------------------------------------------------------------
# I6: Base model RESUME (partial train, then resume)
# ---------------------------------------------------------------------------

def test_i06_base_model_resume(loader, n_jobs):
    """I6: Train model 1 for 1 fold, then resume for remaining folds."""
    output_dir = OUTPUT_BASE / "base_model_resume" / "model1"
    if output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # --- Train fold 0 only ---
    auto_train_base_model(
        model_num=1,
        training_params={},
        output_dir=output_dir,
        metadata_path=METADATA_PATH,
        dataset_name=TEST_DATASET_NAME,
        classification_mode="multiclass",
        reference_class=None,
        diseases=None,
        gene_locus="TCR",
        fold_ids=[TEST_FOLD_IDS[0]],
        data_dir=TEST_RAW_DIR,
        cache_dir=TEST_DATA_DIR,
        gene_reference_path=None,
        n_jobs=n_jobs,
        verbose=0,
        resume=False,
    )

    # Verify fold 0 artifacts exist but no summary (partial)
    fold_0_files = list(output_dir.glob("fold_0_*"))
    assert len(fold_0_files) > 0, "Fold 0 artifacts should exist"

    # --- Resume with all folds ---
    auto_train_base_model(
        model_num=1,
        training_params={},
        output_dir=output_dir,
        metadata_path=METADATA_PATH,
        dataset_name=TEST_DATASET_NAME,
        classification_mode="multiclass",
        reference_class=None,
        diseases=None,
        gene_locus="TCR",
        fold_ids=TEST_FOLD_IDS,
        data_dir=TEST_RAW_DIR,
        cache_dir=TEST_DATA_DIR,
        gene_reference_path=None,
        n_jobs=n_jobs,
        verbose=0,
        resume=True,
    )

    # Verify all folds now have artifacts
    for fid in TEST_FOLD_IDS:
        fold_files = list(output_dir.glob(f"fold_{fid}_*"))
        assert len(fold_files) > 0, f"Fold {fid} artifacts missing after resume"

    # Verify summary was written (all folds complete)
    summary = read_model_summary(output_dir)
    assert summary is not None, "Summary should exist after all folds complete"


# ---------------------------------------------------------------------------
# I7: Mixed LOAD/TRAIN
# ---------------------------------------------------------------------------

def test_i07_mixed_load_train(loader, multiclass_base_models, n_jobs):
    """I7: LOAD model1+model3 from multiclass, train model2 fresh."""
    mc_dirs = multiclass_base_models["model_dirs"]
    mc_summaries = multiclass_base_models["model_summaries"]

    # Fresh model2 output
    m2_output = OUTPUT_BASE / "mixed_load_train" / "model2"
    if m2_output.exists():
        shutil.rmtree(m2_output)
    m2_output.mkdir(parents=True, exist_ok=True)

    auto_train_base_model(
        model_num=2,
        training_params={"glmnet_cv_n_splits": M2_CV_N_SPLITS},
        output_dir=m2_output,
        metadata_path=METADATA_PATH,
        dataset_name=TEST_DATASET_NAME,
        classification_mode="multiclass",
        reference_class=None,
        diseases=None,
        gene_locus="TCR",
        fold_ids=TEST_FOLD_IDS,
        data_dir=TEST_RAW_DIR,
        cache_dir=TEST_DATA_DIR,
        gene_reference_path=None,
        n_jobs=n_jobs,
        verbose=0,
        resume=False,
    )

    # Build mixed model_dirs: LOAD 1+3 from multiclass, LOAD 2 from fresh
    model_dirs = {
        1: mc_dirs[1],
        2: m2_output,
        3: mc_dirs[3],
    }
    model_summaries = {
        1: mc_summaries[1],
        2: read_model_summary(m2_output),
        3: mc_summaries[3],
    }

    output_dir = OUTPUT_BASE / "mixed_load_train" / "ensemble"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=TEST_DATA_DIR / "embeddings",
        run_config={"classification_mode": "multiclass"},
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    assert len(fold_results) == 1
    assert summary["ensemble"]["accuracy_global"] > 0


# ---------------------------------------------------------------------------
# I8: Retrain specific model
# ---------------------------------------------------------------------------

def test_i08_retrain_specific_model(loader, multiclass_base_models, n_jobs):
    """I8: Force retrain model 1 (simulating --retrain-models 1)."""
    # Copy existing model1 artifacts
    original_m1_dir = multiclass_base_models["model_dirs"][1]
    retrain_dir = OUTPUT_BASE / "retrain_specific" / "model1"
    if retrain_dir.exists():
        shutil.rmtree(retrain_dir)
    shutil.copytree(original_m1_dir, retrain_dir)

    # Force retrain (overwrites existing)
    auto_train_base_model(
        model_num=1,
        training_params={},
        output_dir=retrain_dir,
        metadata_path=METADATA_PATH,
        dataset_name=TEST_DATASET_NAME,
        classification_mode="multiclass",
        reference_class=None,
        diseases=None,
        gene_locus="TCR",
        fold_ids=TEST_FOLD_IDS,
        data_dir=TEST_RAW_DIR,
        cache_dir=TEST_DATA_DIR,
        gene_reference_path=None,
        n_jobs=n_jobs,
        verbose=0,
        resume=False,
    )

    summary = read_model_summary(retrain_dir)
    assert summary is not None


# ---------------------------------------------------------------------------
# I9: Classification mode mismatch (LOAD multiclass for binary)
# ---------------------------------------------------------------------------

def test_i09_classification_mode_mismatch(multiclass_base_models):
    """I9: validate_model_summary catches classification mode mismatch."""
    summary = multiclass_base_models["model_summaries"][1]

    expected_config = {
        "gene_locus": "TCR",
        "training_context": TRAINING_CONTEXT,
        "classification_mode": "binary",
        "reference_class": REFERENCE_CLASS,
        "diseases": ["Covid19"],
    }

    with pytest.raises(ValueError, match="classification_mode"):
        validate_model_summary(
            summary, expected_config,
            model_label="Model 1 (mismatch test)",
        )


# ---------------------------------------------------------------------------
# I10: Reference class mismatch
# ---------------------------------------------------------------------------

def test_i10_reference_class_mismatch(binary_base_models):
    """I10: validate_model_summary catches reference_class mismatch."""
    summary = binary_base_models["model_summaries"][1]

    expected_config = {
        "gene_locus": "TCR",
        "training_context": TRAINING_CONTEXT,
        "classification_mode": "binary",
        "reference_class": "HIV",
        "diseases": ["Covid19"],
    }

    with pytest.raises(ValueError, match="reference_class"):
        validate_model_summary(
            summary, expected_config,
            model_label="Model 1 (ref class mismatch)",
        )


# ---------------------------------------------------------------------------
# I11: Disease list mismatch
# ---------------------------------------------------------------------------

def test_i11_disease_list_mismatch(binary_base_models):
    """I11: validate_model_summary catches diseases mismatch."""
    summary = binary_base_models["model_summaries"][1]

    expected_config = {
        "gene_locus": "TCR",
        "training_context": TRAINING_CONTEXT,
        "classification_mode": "binary",
        "reference_class": REFERENCE_CLASS,
        "diseases": ["HIV"],
    }

    with pytest.raises(ValueError, match="diseases"):
        validate_model_summary(
            summary, expected_config,
            model_label="Model 1 (disease mismatch)",
        )


# ---------------------------------------------------------------------------
# I12: Cross-model class mismatch
# ---------------------------------------------------------------------------

def test_i12_cross_model_class_mismatch(multiclass_base_models, binary_base_models):
    """I12: _validate_cross_model_disease_classes detects multiclass vs binary."""
    mc_summary = multiclass_base_models["model_summaries"][1]
    bin_summary = binary_base_models["model_summaries"][1]

    # Only run if both summaries have model_classes
    if "model_classes" not in mc_summary or "model_classes" not in bin_summary:
        pytest.skip("Summaries missing model_classes key")

    mixed_summaries = {
        1: mc_summary,
        2: bin_summary,
    }

    with pytest.raises(ValueError, match="mismatch"):
        _validate_cross_model_disease_classes(mixed_summaries, label="mixed test")


# ---------------------------------------------------------------------------
# I13: Ensemble resume config mismatch
# ---------------------------------------------------------------------------

def test_i13_ensemble_resume_config_mismatch(loader, multiclass_base_models, n_jobs):
    """I13: Resume with changed classification_mode raises ValueError."""
    model_dirs = multiclass_base_models["model_dirs"]
    model_summaries = multiclass_base_models["model_summaries"]

    output_dir = OUTPUT_BASE / "ensemble_resume_mismatch"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    original_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": [TEST_FOLD_IDS[0]],
    }
    embedding_dir = TEST_DATA_DIR / "embeddings"

    # --- Original run ---
    train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        run_config=original_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    # --- Resume with changed config ---
    changed_config = {
        **original_config,
        "classification_mode": "binary",
        "resume": True,
    }

    with pytest.raises(ValueError, match="Cannot resume"):
        train_ensemble(
            loader=loader,
            fold_ids=[TEST_FOLD_IDS[0]],
            model_nums=[1, 2, 3],
            model_dirs={},
            gene_locus="TCR",
            output_dir=output_dir,
            resume=True,
            run_config=changed_config,
            metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
        )


# ---------------------------------------------------------------------------
# I14: Model subset (--models 1 2)
# ---------------------------------------------------------------------------

def test_i14_model_subset(loader, multiclass_base_models, n_jobs):
    """I14: Ensemble with only models 1+2 (no model 3)."""
    model_dirs = {
        1: multiclass_base_models["model_dirs"][1],
        2: multiclass_base_models["model_dirs"][2],
    }
    model_summaries = {
        1: multiclass_base_models["model_summaries"][1],
        2: multiclass_base_models["model_summaries"][2],
    }

    output_dir = OUTPUT_BASE / "ensemble_model_subset"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 2],
        "fold_ids": [TEST_FOLD_IDS[0]],
    }

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 2],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    assert len(fold_results) == 1
    assert summary["ensemble"]["accuracy_global"] > 0
    # Only models 1 and 2 in summary
    assert "model1" in summary["base_models"]
    assert "model2" in summary["base_models"]
    assert "model3" not in summary["base_models"]

    # Feature matrix should only have model 1 and 2 columns
    config_path = output_dir / f"fold_{TEST_FOLD_IDS[0]}_metamodel_config.json"
    with open(config_path) as f:
        config = json.load(f)
    for col in config["feature_columns"]:
        assert "sequence_model" not in col, (
            f"Model 3 column '{col}' should not be in subset ensemble"
        )


# ---------------------------------------------------------------------------
# I15: Fill strategy (fill_0.5) multiclass
# ---------------------------------------------------------------------------

def test_i15_fill_strategy_multiclass(loader, multiclass_base_models, n_jobs):
    """I15: Multiclass ensemble with fill_0.5 strategy.

    Uses multiclass base models (where M2 has real partial abstentions).
    Verifies fill artifacts, fill_info in results JSON, and that filled
    specimens appear in the feature matrix.
    """
    model_dirs = multiclass_base_models["model_dirs"]
    model_summaries = multiclass_base_models["model_summaries"]

    output_dir = OUTPUT_BASE / "ensemble_fill_multiclass"
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "multiclass",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": [TEST_FOLD_IDS[0]],
        "model2_abstention_strategy": "fill_0.5",
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        disease_filter=None,
        reference_class=None,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
        model2_abstention_strategy="fill_0.5",
    )

    assert len(fold_results) == 1
    fr = fold_results[0]

    # --- Fill info should be populated (or M2 excluded if fully abstained) ---
    test_fill = fr.get("test_fill_info", {})
    val_fill = fr.get("val_fill_info", {})

    m2_excluded = 2 in test_fill.get("excluded_models", [])
    if m2_excluded:
        # M2 fully abstained — excluded, no fills
        assert test_fill.get("n_filled") is None or test_fill.get("n_filled", 0) == 0
    else:
        # M2 partially abstained — fills should have happened (or no abstentions)
        if test_fill.get("n_filled", 0) > 0:
            assert test_fill["strategy"] == "fill_0.5"
            assert len(test_fill["filled_specimen_labels"]) == test_fill["n_filled"]

    # --- Verify results JSON has fill info ---
    results_json = output_dir / f"fold_{TEST_FOLD_IDS[0]}_ensemble_results.json"
    assert results_json.exists()
    with open(results_json) as f:
        results = json.load(f)
    assert "test_fill_info" in results
    assert "val_fill_info" in results

    # --- Raw feature matrices should be saved ---
    raw_test = output_dir / f"fold_{TEST_FOLD_IDS[0]}_feature_matrix_raw_test.csv"
    raw_val = output_dir / f"fold_{TEST_FOLD_IDS[0]}_feature_matrix_raw_val.csv"
    assert raw_test.exists(), "Raw test feature matrix should be saved"
    assert raw_val.exists(), "Raw validation feature matrix should be saved"

    # --- Verify raw matrix has NaN in M2 columns for filled specimens ---
    if not m2_excluded and test_fill.get("n_filled", 0) > 0:
        raw_df = pd.read_csv(raw_test, index_col="specimen_label")
        m2_cols = [c for c in raw_df.columns
                   if "convergent_cluster_model" in c and c != "true_disease"]
        if m2_cols:
            filled_labels = test_fill["filled_specimen_labels"]
            for spec in filled_labels:
                if spec in raw_df.index:
                    assert raw_df.loc[spec, m2_cols].isna().all(), (
                        f"Raw matrix should have NaN for filled specimen {spec}"
                    )

    # --- Ensemble n_abstained should be 0 (fill keeps all specimens) ---
    ens_metrics = fr["ensemble_metrics"]
    assert ens_metrics["n_abstained"] == 0, (
        f"With fill strategy, ensemble n_abstained should be 0, got {ens_metrics['n_abstained']}"
    )

    # --- Predictions CSV: no specimens should be 'ABSTAINED' ---
    preds_df = pd.read_csv(output_dir / "ensemble_predictions.csv")
    assert (preds_df["ensemble_predicted"] != "ABSTAINED").all(), (
        "With fill strategy, no specimens should be ABSTAINED"
    )

    # --- MD should mention fill strategy ---
    md_files = list(output_dir.glob("RESULTS_*.md"))
    assert len(md_files) == 1
    md_text = md_files[0].read_text()
    assert "fill_0.5" in md_text


# ---------------------------------------------------------------------------
# I16: Binary with M2 exclusion verification
# ---------------------------------------------------------------------------

def test_i16_binary_m2_exclusion(loader, binary_base_models, n_jobs):
    """I16: Binary ensemble where M2 fully abstains — verify exclusion explicitly.

    The test data's binary subset is too small for M2 to find valid convergent
    clusters, so M2 fully abstains. Verify M2 is excluded from the ensemble,
    no M2 columns in feature matrix, and ensemble n_abstained is 0.
    """
    model_dirs = binary_base_models["model_dirs"]
    model_summaries = binary_base_models["model_summaries"]
    disease = binary_base_models["disease"]
    disease_filter = (disease, REFERENCE_CLASS)

    output_dir = OUTPUT_BASE / "ensemble_binary_m2_exclusion" / binary_base_models["pair_name"]
    if output_dir.exists():
        shutil.rmtree(output_dir)

    run_config = {
        "dataset_name": TEST_DATASET_NAME,
        "classification_mode": "binary",
        "gene_locus": "TCR",
        "models_included": [1, 2, 3],
        "fold_ids": [TEST_FOLD_IDS[0]],
        "disease_filter": list(disease_filter),
        "reference_class": REFERENCE_CLASS,
    }

    embedding_dir = TEST_DATA_DIR / "embeddings"

    fold_results, summary = train_ensemble(
        loader=loader,
        fold_ids=[TEST_FOLD_IDS[0]],
        model_nums=[1, 2, 3],
        model_dirs=model_dirs,
        gene_locus="TCR",
        output_dir=output_dir,
        embedding_dir=embedding_dir,
        disease_filter=disease_filter,
        reference_class=REFERENCE_CLASS,
        run_config=run_config,
        model_summaries=model_summaries,
        n_jobs=n_jobs,
        metamodel_cv_n_splits=METAMODEL_CV_N_SPLITS,
    )

    assert len(fold_results) == 1
    fr = fold_results[0]

    # --- M2 should be excluded (fully abstained) ---
    test_fill = fr.get("test_fill_info", {})
    assert 2 in test_fill.get("excluded_models", []), (
        f"M2 should be excluded from binary ensemble, test_fill_info: {test_fill}"
    )

    # --- No M2 columns in feature matrix ---
    config_path = output_dir / f"fold_{TEST_FOLD_IDS[0]}_metamodel_config.json"
    with open(config_path) as f:
        config = json.load(f)
    for col in config["feature_columns"]:
        assert "convergent_cluster_model" not in col, (
            f"M2 column '{col}' should not appear when M2 is excluded"
        )

    # --- M2 not in base model metrics ---
    assert 2 not in fr["base_model_metrics"], (
        "M2 should not have base model metrics when fully excluded"
    )

    # --- Ensemble n_abstained should be 0 (M2 excluded, M1+M3 score all) ---
    ens_metrics = fr["ensemble_metrics"]
    assert ens_metrics["n_abstained"] == 0, (
        f"With M2 excluded, ensemble n_abstained should be 0, got {ens_metrics['n_abstained']}"
    )

    # --- Summary should report exclusion ---
    assert 2 in summary.get("models_excluded", []), (
        f"Summary should list M2 as excluded, got: {summary.get('models_excluded')}"
    )

    # --- MD should have exclusion warning ---
    md_files = list(output_dir.glob("RESULTS_*.md"))
    assert len(md_files) == 1
    md_text = md_files[0].read_text()
    assert "Models Excluded from Ensemble" in md_text
