"""Comprehensive test suite for Model 1 (Repertoire Classifier).

Tests the full Model 1 pipeline in two tiers:

  Tier 1 -- Unit tests with SYNTHETIC data (no cache, no GPU, ~30-60 seconds):
    Fast tests that exercise individual components using small fabricated datasets.
    These run even without a data cache or test data directory.

  Tier 2 -- Integration tests with TEST DATA (tests/test_data/, ~5-15 min):
    End-to-end tests that run the full training pipeline on the small test
    dataset (~118K sequences, 72 participants, 3 folds, 4 diseases).
    Uses create_test_loader() from test_helpers.py.

Tests
-----
Unit tests (synthetic data):
  1.  validate_training_params: valid, n_pcs < 1, l1_ratio out of range, None
  2.  validate_mode_and_classes: multiclass, binary, multi-binary, unknown mode
  3.  filter_to_binary_pair: filtering, excluded classes, empty result
  4.  evaluate_on_test: multiclass (3+ classes), binary (2 classes)
  5.  aggregate_fold_results: multiclass, binary, all-abstained
  6.  RepertoireClassifier: constructor validation, BCR rejection, extract_features
  7.  Resume helpers: artifact paths, fold complete, legacy, save/load, validate_meta
  8.  Output path logic: get_model_output_dir, suffix, training context
  9.  filter_rare_v_genes: basic filtering
  10. make_pair_name: sanitization

Integration tests (test data):
  11. Multiclass pipeline (all 3 folds via train_all_folds)
  12. Binary pipeline (1 disease vs Healthy/Background)
  13. Multi-binary pipeline (explicit diseases + auto-detect all diseases)
  14. cv_ensemble training context
  15. output_suffix
  16. Resume: original run -> resume -> metrics match
  17. Resume: incomplete fold -> retrain
  18. Resume: parameter mismatch -> ValueError
  19. PCA n_pcs cap (n_pcs > n_samples)
  20. RepertoireClassifier save/load round-trip
  21. Predictions CSV format (multiclass and binary)
  22. Bad arg combinations (binary without ref, multi-binary ref in diseases, etc.)
  23. Summary JSON structure and completeness

Design notes
------------
- Uses pytest for discovery and parametrize for combinatorial cases.
- Unit tests build synthetic DataFrames; integration tests use test_data/.
- Integration tests use create_test_loader() from test_helpers.py.

Requirements
------------
- Tier 1 (unit): numpy, pandas, scikit-learn
- Tier 2 (integration): glmnet, test_data/ (generated by create_test_data.py)

Expected runtime
----------------
- Tier 1 only: ~30-60 seconds
- Tier 1 + Tier 2: ~5-15 minutes

Running
-------
From Mal-ID-Lite root directory:

    # Unit tests only (~30-60 seconds)
    python -m pytest tests/test_model1.py -v -s -k "not integration"

    # Full suite
    python -m pytest tests/test_model1.py -v -s
"""

import json
import logging
import pickle
import shutil
import sys
import time
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import pytest

# Project root (tests/ -> project root)
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from test_helpers import TEST_DATA_DIR, TEST_RAW_DIR

from malid_lite.models.model1_repertoire import RepertoireClassifier, V_GENE_COL, J_GENE_COL
from malid_lite.training.train_model1 import (
    _check_fold_complete,
    _check_fold_has_legacy_artifacts,
    _get_fold_artifact_paths,
    _load_fold_results,
    _MIN_PKL_BYTES,
    _run_fold_loop,
    _save_fold_predictions,
    _validate_fold_meta,
    evaluate_on_test,
    filter_rare_v_genes,
    train_all_folds,
    validate_training_params,
)
from malid_lite.training.training_utils import (
    DISEASE_COL,
    PARTICIPANT_COL,
    SPECIMEN_COL,
    VALID_TRAINING_CONTEXTS,
    aggregate_fold_results,
    filter_to_binary_pair,
    get_model_output_dir,
    make_pair_name,
    validate_mode_and_classes,
)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

# ---------------------------------------------------------------------------
# Output directory for test artifacts
# ---------------------------------------------------------------------------

_TEST_OUTPUT_DIR = Path(__file__).parent / "test_outputs" / Path(__file__).stem
_TEST_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Synthetic data helpers
# ---------------------------------------------------------------------------

def _make_synthetic_sequences(
    n_specimens: int = 20,
    n_sequences_per_specimen: int = 100,
    diseases: List[str] = None,
    n_participants_per_disease: int = 5,
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Create synthetic sequences and metadata for unit tests.

    Returns (sequences_df, metadata_df) with realistic column structure.
    """
    if diseases is None:
        diseases = ["Covid19", "HIV", "Healthy/Background"]

    rng = np.random.RandomState(42)
    v_genes = [f"TRBV{i}" for i in range(1, 16)]
    j_genes = [f"TRBJ{i}" for i in range(1, 8)]

    all_seqs = []
    all_meta = []
    participant_idx = 0

    for disease in diseases:
        for p in range(n_participants_per_disease):
            participant_label = f"P{participant_idx:04d}"
            specimen_label = f"S{participant_idx:04d}"
            participant_idx += 1

            for _ in range(n_sequences_per_specimen):
                all_seqs.append({
                    "specimen_label": specimen_label,
                    "participant_label": participant_label,
                    "v_gene": rng.choice(v_genes),
                    "j_gene": rng.choice(j_genes),
                    "isotype_supergroup": "TCRB",
                    "cdr3_aa": "CASSLGX",
                })

            all_meta.append({
                "specimen_label": specimen_label,
                "participant_label": participant_label,
                "disease": disease,
                "CV_fold": participant_idx % 3,
            })

    sequences_df = pd.DataFrame(all_seqs)
    metadata_df = pd.DataFrame(all_meta)
    return sequences_df, metadata_df


def _make_synthetic_predictions(
    n_samples: int = 30,
    n_classes: int = 4,
    class_names: List[str] = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Create synthetic predictions for evaluate_on_test tests.

    Returns (y_true, y_pred, y_proba, classes).
    """
    rng = np.random.RandomState(42)
    if class_names is None:
        class_names = [f"Class{i}" for i in range(n_classes)]
    classes = np.array(class_names)

    y_true = rng.choice(classes, size=n_samples)
    y_proba = rng.dirichlet(np.ones(n_classes), size=n_samples)
    y_pred = classes[y_proba.argmax(axis=1)]

    return y_true, y_pred, y_proba, classes


def _make_fake_complete_fold(
    output_dir: Path,
    fold_id: int,
    model_name: str,
    model_params: dict = None,
    training_context: str = "cv_single_model",
) -> List[Path]:
    """Create all 4 fold artifacts with realistic sizes for testing."""
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = _get_fold_artifact_paths(output_dir, fold_id, model_name)

    if model_params is None:
        model_params = {"gene_locus": "TCR", "n_pcs": 15, "l1_ratio": 1.0}

    # model.pkl -- needs to be >= _MIN_PKL_BYTES
    model_data = {"weights": np.random.randn(100).tolist(), "padding": "x" * 2000}
    with open(paths[0], "wb") as f:
        pickle.dump(model_data, f)

    # v_genes.json
    with open(paths[1], "w") as f:
        json.dump(["TRBV1", "TRBV2", "TRBV3"], f)

    # results.json
    eval_results = {
        "fold_id": fold_id,
        "model_name": model_name,
        "accuracy": 0.75,
        "mcc": 0.60,
        "auroc_ovo_weighted": 0.90,
        "n_scored": 50,
        "n_abstained": 0,
    }
    with open(paths[2], "w") as f:
        json.dump(eval_results, f)

    # predictions.pkl -- with _meta
    n_samples = 50
    raw_preds = {
        "y_true": np.array(["A", "B"] * (n_samples // 2)),
        "y_pred": np.array(["A", "B"] * (n_samples // 2)),
        "y_proba": np.random.rand(n_samples, 2),
        "classes": np.array(["A", "B"]),
    }
    predictions_rows = [
        {"specimen_label": f"s{i}", "true_disease": "A" if i % 2 == 0 else "B",
         "predicted_disease": "A"}
        for i in range(n_samples)
    ]
    preds_data = {
        "raw_preds": raw_preds,
        "predictions_rows": predictions_rows,
        "_meta": {
            "model_name": model_name,
            "model_params": model_params,
            "training_context": training_context,
            "fold_id": fold_id,
        },
    }
    with open(paths[3], "wb") as f:
        pickle.dump(preds_data, f)

    # Verify pkl sizes are above threshold
    for p in [paths[0], paths[3]]:
        assert p.stat().st_size >= _MIN_PKL_BYTES, (
            f"Test setup bug: {p.name} is {p.stat().st_size} bytes, "
            f"expected >= {_MIN_PKL_BYTES}"
        )

    return paths


def _clean_dir(path: Path) -> Path:
    """Remove and recreate a directory."""
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)
    return path


# ---------------------------------------------------------------------------
# Tier 1: Unit tests — validate_training_params
# ---------------------------------------------------------------------------

class TestValidateTrainingParams:
    """Tests for validate_training_params (parameter range validation)."""

    def test_valid_defaults(self):
        """Default None values pass without error."""
        validate_training_params()

    def test_valid_n_pcs(self):
        """Valid n_pcs values pass."""
        validate_training_params(n_pcs=1)
        validate_training_params(n_pcs=15)
        validate_training_params(n_pcs=100)

    def test_valid_l1_ratio(self):
        """Valid l1_ratio values at boundaries and interior."""
        validate_training_params(l1_ratio=0.0)
        validate_training_params(l1_ratio=0.5)
        validate_training_params(l1_ratio=1.0)

    def test_n_pcs_zero_raises(self):
        """n_pcs=0 should raise ValueError."""
        with pytest.raises(ValueError, match="n_pcs must be >= 1"):
            validate_training_params(n_pcs=0)

    def test_n_pcs_negative_raises(self):
        """Negative n_pcs should raise ValueError."""
        with pytest.raises(ValueError, match="n_pcs must be >= 1"):
            validate_training_params(n_pcs=-5)

    def test_l1_ratio_below_zero_raises(self):
        """l1_ratio < 0.0 should raise ValueError."""
        with pytest.raises(ValueError, match="l1_ratio must be in"):
            validate_training_params(l1_ratio=-0.1)

    def test_l1_ratio_above_one_raises(self):
        """l1_ratio > 1.0 should raise ValueError."""
        with pytest.raises(ValueError, match="l1_ratio must be in"):
            validate_training_params(l1_ratio=1.1)

    def test_l1_ratio_none_skips_check(self):
        """l1_ratio=None should skip validation (use default)."""
        validate_training_params(l1_ratio=None)

    def test_n_pcs_none_skips_check(self):
        """n_pcs=None should skip validation (use default)."""
        validate_training_params(n_pcs=None)

    def test_both_invalid(self):
        """First invalid param hit raises (n_pcs checked before l1_ratio)."""
        with pytest.raises(ValueError, match="n_pcs"):
            validate_training_params(n_pcs=0, l1_ratio=2.0)

    def test_extra_kwargs_ignored(self):
        """Extra kwargs are silently ignored."""
        validate_training_params(n_pcs=15, l1_ratio=0.5, unknown_param="foo")


# ---------------------------------------------------------------------------
# Tier 1: validate_mode_and_classes
# ---------------------------------------------------------------------------

class TestValidateModeAndClasses:
    """Tests for validate_mode_and_classes (mode/data compatibility)."""

    CLASSES_4 = ["Covid19", "HIV", "Healthy/Background", "T1D"]
    CLASSES_2 = ["Covid19", "Healthy/Background"]
    REF = "Healthy/Background"

    # --- Multiclass ---

    def test_multiclass_4_classes(self):
        """Multiclass with 4 classes passes, returns reference_class as-is."""
        result = validate_mode_and_classes("multiclass", self.CLASSES_4, None)
        assert result is None

    def test_multiclass_2_classes(self):
        """Multiclass with 2 classes proceeds (binary multiclass)."""
        result = validate_mode_and_classes("multiclass", self.CLASSES_2, None)
        assert result is None

    def test_multiclass_with_diseases_raises(self):
        """Multiclass mode does not support --diseases."""
        with pytest.raises(ValueError, match="--diseases is not supported in multiclass"):
            validate_mode_and_classes("multiclass", self.CLASSES_4, None, diseases=["HIV"])

    def test_multiclass_with_reference_class_warns(self):
        """Multiclass with reference_class should warn but not error."""
        result = validate_mode_and_classes("multiclass", self.CLASSES_4, self.REF)
        assert result == self.REF

    # --- Binary ---

    def test_binary_2_classes(self):
        """Binary with 2 classes passes."""
        result = validate_mode_and_classes("binary", self.CLASSES_2, self.REF)
        assert result == self.REF

    def test_binary_no_reference_raises(self):
        """Binary without reference_class raises."""
        with pytest.raises(ValueError, match="--reference-class is required"):
            validate_mode_and_classes("binary", self.CLASSES_2, None)

    def test_binary_reference_not_in_data_raises(self):
        """Binary with reference class not in data raises."""
        with pytest.raises(ValueError, match="not found in data classes"):
            validate_mode_and_classes("binary", self.CLASSES_2, "Unknown")

    def test_binary_4_classes_no_diseases_raises(self):
        """Binary with 4 classes and no --diseases raises."""
        with pytest.raises(ValueError, match="exactly 2 disease classes"):
            validate_mode_and_classes("binary", self.CLASSES_4, self.REF)

    def test_binary_4_classes_with_diseases_passes(self):
        """Binary with 4 classes but --diseases picks one disease."""
        result = validate_mode_and_classes(
            "binary", self.CLASSES_4, self.REF, diseases=["HIV"]
        )
        assert result == self.REF

    # --- Multi-binary ---

    def test_multi_binary_no_reference_raises(self):
        """Multi-binary without reference_class raises."""
        with pytest.raises(ValueError, match="--reference-class is required"):
            validate_mode_and_classes("multi-binary", self.CLASSES_4, None)

    def test_multi_binary_reference_not_in_data_raises(self):
        """Multi-binary with unknown reference raises."""
        with pytest.raises(ValueError, match="not found in data classes"):
            validate_mode_and_classes("multi-binary", self.CLASSES_4, "Unknown")

    def test_multi_binary_passes(self):
        """Multi-binary with valid reference passes."""
        result = validate_mode_and_classes("multi-binary", self.CLASSES_4, self.REF)
        assert result == self.REF

    def test_multi_binary_with_diseases(self):
        """Multi-binary with explicit diseases subset passes."""
        result = validate_mode_and_classes(
            "multi-binary", self.CLASSES_4, self.REF, diseases=["HIV", "Covid19"]
        )
        assert result == self.REF

    # --- Unknown mode ---

    def test_unknown_mode_raises(self):
        """Unknown classification mode raises ValueError."""
        with pytest.raises(ValueError, match="Unknown classification_mode"):
            validate_mode_and_classes("unknown_mode", self.CLASSES_4, None)


# ---------------------------------------------------------------------------
# Tier 1: filter_to_binary_pair
# ---------------------------------------------------------------------------

class TestFilterToBinaryPair:
    """Tests for filter_to_binary_pair (data filtering for binary mode)."""

    def setup_method(self):
        self.seqs, self.meta = _make_synthetic_sequences(
            n_specimens=20,
            n_sequences_per_specimen=50,
            diseases=["Covid19", "HIV", "Healthy/Background", "T1D"],
            n_participants_per_disease=5,
        )

    def test_filters_to_two_classes(self):
        """Only disease and reference_class remain after filtering."""
        filtered_seqs, filtered_meta = filter_to_binary_pair(
            self.seqs, self.meta, "HIV", "Healthy/Background"
        )
        assert set(filtered_meta[DISEASE_COL].unique()) == {"HIV", "Healthy/Background"}

    def test_excluded_classes_absent(self):
        """Excluded classes have zero rows in both DataFrames."""
        filtered_seqs, filtered_meta = filter_to_binary_pair(
            self.seqs, self.meta, "HIV", "Healthy/Background"
        )
        # Covid19 and T1D participants should not appear
        excluded_participants = set(
            self.meta.loc[
                self.meta[DISEASE_COL].isin({"Covid19", "T1D"}), PARTICIPANT_COL
            ]
        )
        assert not filtered_seqs[PARTICIPANT_COL].isin(excluded_participants).any()
        assert not filtered_meta[PARTICIPANT_COL].isin(excluded_participants).any()

    def test_specimen_consistency(self):
        """Sequences reference only specimens present in filtered metadata."""
        filtered_seqs, filtered_meta = filter_to_binary_pair(
            self.seqs, self.meta, "Covid19", "Healthy/Background"
        )
        meta_specimens = set(filtered_meta[SPECIMEN_COL])
        seq_specimens = set(filtered_seqs[SPECIMEN_COL].unique())
        assert seq_specimens.issubset(meta_specimens)

    def test_row_counts_decrease(self):
        """Filtering to 2 of 4 classes should reduce data."""
        filtered_seqs, filtered_meta = filter_to_binary_pair(
            self.seqs, self.meta, "HIV", "Healthy/Background"
        )
        assert len(filtered_meta) < len(self.meta)
        assert len(filtered_seqs) < len(self.seqs)


# ---------------------------------------------------------------------------
# Tier 1: evaluate_on_test
# ---------------------------------------------------------------------------

class TestEvaluateOnTest:
    """Tests for evaluate_on_test (per-fold evaluation metrics)."""

    def test_multiclass_metrics(self):
        """Multiclass (4 classes) produces AUROC OvO, AUPRC, confusion matrix."""
        y_true, y_pred, y_proba, classes = _make_synthetic_predictions(
            n_samples=40, n_classes=4,
            class_names=["Covid19", "HIV", "Healthy/Background", "T1D"],
        )
        metrics, raw_preds = evaluate_on_test(
            y_true, y_pred, y_proba, classes,
            fold_id=0, model_name="lasso_cv", n_train=100, n_test=40, n_features=50,
        )

        assert metrics["fold_id"] == 0
        assert metrics["model_name"] == "lasso_cv"
        assert 0.0 <= metrics["accuracy"] <= 1.0
        assert metrics["n_scored"] == 40
        assert metrics["n_abstained"] == 0
        assert metrics["auroc_ovo_weighted"] is not None
        assert metrics["auprc_ovo_weighted"] is not None
        assert metrics["auroc_ovr_per_class"] is not None
        assert len(metrics["auroc_ovr_per_class"]) == 4
        assert metrics["confusion_matrix"] is not None
        assert len(metrics["classes"]) == 4
        assert metrics["mcc"] is not None

        # raw_preds structure
        assert set(raw_preds.keys()) == {"y_true", "y_pred", "y_proba", "classes"}
        assert len(raw_preds["y_true"]) == 40

    def test_binary_metrics(self):
        """Binary (2 classes) produces auroc_binary and auprc_binary."""
        y_true, y_pred, y_proba, classes = _make_synthetic_predictions(
            n_samples=30, n_classes=2,
            class_names=["HIV", "Healthy/Background"],
        )
        metrics, raw_preds = evaluate_on_test(
            y_true, y_pred, y_proba, classes,
            fold_id=1, model_name="lasso_cv", n_train=80, n_test=30, n_features=50,
            reference_class="Healthy/Background",
        )

        assert metrics["auroc_binary"] is not None
        assert 0.0 <= metrics["auroc_binary"] <= 1.0
        assert metrics["auprc_binary"] is not None
        assert 0.0 <= metrics["auprc_binary"] <= 1.0
        # Multiclass metrics should be None for 2 classes
        assert metrics["auroc_ovo_weighted"] is None
        assert metrics["auroc_ovr_per_class"] is None

    def test_binary_no_reference(self):
        """Binary (2 classes) without reference_class skips auroc_binary."""
        y_true, y_pred, y_proba, classes = _make_synthetic_predictions(
            n_samples=30, n_classes=2,
            class_names=["HIV", "Healthy/Background"],
        )
        metrics, _ = evaluate_on_test(
            y_true, y_pred, y_proba, classes,
            fold_id=0, model_name="lasso_cv", n_train=80, n_test=30, n_features=50,
            reference_class=None,
        )
        assert "auroc_binary" not in metrics

    def test_zero_test_specimens(self):
        """Zero test specimens raises ValueError (sklearn rejects empty arrays)."""
        y_true = np.array([], dtype=str)
        y_pred = np.array([], dtype=str)
        y_proba = np.zeros((0, 2))
        classes = np.array(["A", "B"])
        with pytest.raises(ValueError, match="empty"):
            evaluate_on_test(
                y_true, y_pred, y_proba, classes,
                fold_id=0, model_name="lasso_cv", n_train=10, n_test=0, n_features=5,
            )


# ---------------------------------------------------------------------------
# Tier 1: aggregate_fold_results
# ---------------------------------------------------------------------------

class TestAggregateFoldResults:
    """Tests for aggregate_fold_results (cross-fold aggregation)."""

    def test_multiclass_aggregation(self):
        """Multiclass aggregation produces all expected keys."""
        classes = np.array(["A", "B", "C"])
        fold_metrics = []
        fold_raw_preds = []
        rng = np.random.RandomState(42)

        for fold_id in range(3):
            n = 20
            y_true = rng.choice(classes, size=n)
            y_proba = rng.dirichlet(np.ones(3), size=n)
            y_pred = classes[y_proba.argmax(axis=1)]

            metrics, raw_preds = evaluate_on_test(
                y_true, y_pred, y_proba, classes,
                fold_id=fold_id, model_name="lasso_cv",
                n_train=50, n_test=n, n_features=30,
            )
            fold_metrics.append(metrics)
            fold_raw_preds.append(raw_preds)

        agg = aggregate_fold_results(fold_metrics, fold_raw_preds, disease_filter=None)

        assert agg["n_folds"] == 3
        assert agg["n_folds_scored"] == 3
        assert "accuracy_global" in agg
        assert "confusion_matrix_aggregated" in agg
        assert "accuracy_per_fold" in agg
        assert agg["accuracy_per_fold"]["n_folds_valid"] == 3

    def test_binary_aggregation(self):
        """Binary aggregation produces auroc_pooled, auprc_pooled."""
        classes = np.array(["HIV", "Healthy/Background"])
        fold_metrics = []
        fold_raw_preds = []
        rng = np.random.RandomState(42)

        for fold_id in range(3):
            n = 20
            y_true = rng.choice(classes, size=n)
            y_proba = rng.dirichlet(np.ones(2), size=n)
            y_pred = classes[y_proba.argmax(axis=1)]

            metrics, raw_preds = evaluate_on_test(
                y_true, y_pred, y_proba, classes,
                fold_id=fold_id, model_name="lasso_cv",
                n_train=50, n_test=n, n_features=30,
                reference_class="Healthy/Background",
            )
            metrics["disease"] = "HIV"
            metrics["reference_class"] = "Healthy/Background"
            fold_metrics.append(metrics)
            fold_raw_preds.append(raw_preds)

        agg = aggregate_fold_results(
            fold_metrics, fold_raw_preds,
            disease_filter=("HIV", "Healthy/Background"),
        )

        assert agg["auroc_pooled"] is not None
        assert 0.0 <= agg["auroc_pooled"] <= 1.0
        assert agg["auprc_pooled"] is not None
        assert agg["disease"] == "HIV"
        assert agg["reference_class"] == "Healthy/Background"

    def test_single_fold_pooled_equals_per_fold(self):
        """With 1 fold, pooled AUROC equals that fold's binary AUROC."""
        classes = np.array(["HIV", "Healthy/Background"])
        rng = np.random.RandomState(42)
        n = 30
        y_true = rng.choice(classes, size=n)
        y_proba = rng.dirichlet(np.ones(2), size=n)
        y_pred = classes[y_proba.argmax(axis=1)]

        metrics, raw_preds = evaluate_on_test(
            y_true, y_pred, y_proba, classes,
            fold_id=0, model_name="lasso_cv",
            n_train=50, n_test=n, n_features=30,
            reference_class="Healthy/Background",
        )
        metrics["disease"] = "HIV"
        metrics["reference_class"] = "Healthy/Background"

        agg = aggregate_fold_results(
            [metrics], [raw_preds],
            disease_filter=("HIV", "Healthy/Background"),
        )

        assert abs(agg["auroc_pooled"] - metrics["auroc_binary"]) < 1e-9

    def test_all_none_raw_preds(self):
        """All-None raw_preds returns a warning dict."""
        metrics = [{"fold_id": 0, "n_scored": 0, "n_abstained": 10, "accuracy": 0.0}]
        agg = aggregate_fold_results(metrics, [None], disease_filter=None)
        assert agg["n_folds_scored"] == 0
        assert "warning" in agg


# ---------------------------------------------------------------------------
# Tier 1: RepertoireClassifier constructor
# ---------------------------------------------------------------------------

class TestRepertoireClassifier:
    """Tests for RepertoireClassifier construction and validation."""

    def test_default_tcr(self):
        """Default TCR constructor sets expected defaults."""
        model = RepertoireClassifier()
        assert model.gene_locus == "TCR"
        assert model.n_pcs == 15
        assert model.l1_ratio == 1.0  # TCR default
        assert model.is_fitted_ is False

    def test_custom_params(self):
        """Custom constructor params are stored correctly."""
        model = RepertoireClassifier(
            gene_locus="TCR", n_pcs=10, l1_ratio=0.5, n_lambda=50,
        )
        assert model.n_pcs == 10
        assert model.l1_ratio == 0.5
        assert model.n_lambda == 50

    def test_invalid_gene_locus_raises(self):
        """Invalid gene_locus raises ValueError."""
        with pytest.raises(ValueError, match="gene_locus must be"):
            RepertoireClassifier(gene_locus="INVALID")

    def test_bcr_not_implemented(self):
        """BCR raises NotImplementedError."""
        with pytest.raises(NotImplementedError, match="BCR support not yet"):
            RepertoireClassifier(gene_locus="BCR")

    def test_predict_before_fit_raises(self):
        """predict() before fit() raises RuntimeError."""
        model = RepertoireClassifier()
        dummy_X = pd.DataFrame({"col": [1, 2]})
        with pytest.raises(RuntimeError, match="must be fitted"):
            model.predict(dummy_X)

    def test_predict_proba_before_fit_raises(self):
        """predict_proba() before fit() raises RuntimeError."""
        model = RepertoireClassifier()
        dummy_X = pd.DataFrame({"col": [1, 2]})
        with pytest.raises(RuntimeError, match="must be fitted"):
            model.predict_proba(dummy_X)

    def test_repr_unfitted(self):
        """repr shows 'not fitted' for unfitted model."""
        model = RepertoireClassifier(n_pcs=10, l1_ratio=0.5)
        r = repr(model)
        assert "not fitted" in r
        assert "n_pcs=10" in r
        assert "l1_ratio=0.5" in r

    def test_default_l1_ratios(self):
        """DEFAULT_L1_RATIOS has expected values."""
        assert RepertoireClassifier.DEFAULT_L1_RATIOS["TCR"] == 1.0
        assert RepertoireClassifier.DEFAULT_L1_RATIOS["BCR"] == 0.25

    def test_l1_ratio_none_uses_default(self):
        """l1_ratio=None uses DEFAULT_L1_RATIOS for the gene_locus."""
        model = RepertoireClassifier(gene_locus="TCR", l1_ratio=None)
        assert model.l1_ratio == 1.0

    def test_extract_features_column_alignment(self):
        """Test that extract_features aligns test columns to train columns.

        When test data has V-J pairs not in training (and training has pairs not
        in test), the feature matrix should:
        - Add missing train columns filled with 0
        - Drop test-only columns not in train
        - Result in same column count as training
        """
        model = RepertoireClassifier(gene_locus="TCR", n_pcs=5, verbose=0)
        rng = np.random.RandomState(42)

        # Build synthetic sequences for 2 "specimens"
        def _make_seqs(specimen_ids, v_genes, n_per_specimen=50):
            rows = []
            for sid in specimen_ids:
                for _ in range(n_per_specimen):
                    rows.append({
                        "specimen_label": sid,
                        "participant_label": f"P_{sid}",
                        "v_gene": rng.choice(v_genes),
                        "j_gene": rng.choice(["TRBJ1", "TRBJ2"]),
                        "isotype_supergroup": "TCRB",
                    })
            return pd.DataFrame(rows)

        # Train: specimens S1, S2 with V genes TRBV1-TRBV5
        train_seqs = _make_seqs(["S1", "S2"], [f"TRBV{i}" for i in range(1, 6)])
        X_train = model.extract_features(train_seqs)
        train_vj_cols = model.train_vj_columns_  # not set yet (only set in fit)

        # Manually capture train column structure (extract_features doesn't set
        # train_vj_columns_ — fit() does that). Simulate what fit() does:
        train_vj_columns = {}
        for isotype in model.isotype_groups_:
            cols = X_train.columns[X_train.columns.str.endswith(f":{isotype}")]
            train_vj_columns[isotype] = cols

        # Test: specimens S3, S4 with V genes TRBV3-TRBV7 (overlap: TRBV3-5,
        # new in test: TRBV6-7, missing from test: TRBV1-2)
        test_seqs = _make_seqs(["S3", "S4"], [f"TRBV{i}" for i in range(3, 8)])
        X_test = model.extract_features(
            test_seqs, train_vj_columns=train_vj_columns,
        )

        # Test features should have same columns as train
        assert X_test.shape[1] == X_train.shape[1], (
            f"Column count mismatch: train={X_train.shape[1]}, test={X_test.shape[1]}"
        )
        assert list(X_test.columns) == list(X_train.columns)

        # Test should have 2 specimens
        assert X_test.shape[0] == 2
        assert set(X_test.index) == {"S3", "S4"}


# ---------------------------------------------------------------------------
# Tier 1: Resume helpers (artifact detection, save/load, validation)
# ---------------------------------------------------------------------------

class TestResumeHelpers:
    """Tests for per-fold resume support helpers."""

    MODEL_NAME = "lasso_cv"
    MODEL_PARAMS = {"gene_locus": "TCR", "n_pcs": 15, "l1_ratio": 1.0}
    TRAINING_CONTEXT = "cv_single_model"

    def _get_dir(self, name: str) -> Path:
        return _clean_dir(_TEST_OUTPUT_DIR / "resume_helpers" / name)

    # --- _get_fold_artifact_paths ---

    def test_artifact_paths_count_and_names(self):
        """Returns 4 paths with correct names."""
        paths = _get_fold_artifact_paths(Path("/tmp"), 2, "lasso_cv")
        assert len(paths) == 4
        names = [p.name for p in paths]
        assert names == [
            "fold_2_lasso_cv_model.pkl",
            "fold_2_lasso_cv_v_genes.json",
            "fold_2_lasso_cv_results.json",
            "fold_2_lasso_cv_predictions.pkl",
        ]

    def test_artifact_paths_parent_dir(self):
        """All paths share the given parent directory."""
        d = Path("/some/dir")
        for p in _get_fold_artifact_paths(d, 0, "lasso_cv"):
            assert p.parent == d

    # --- _check_fold_complete ---

    def test_complete_all_present(self):
        """All 4 artifacts present and large enough -> True."""
        d = self._get_dir("complete_yes")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        assert _check_fold_complete(d, 0, self.MODEL_NAME) is True

    def test_complete_missing_one_file(self):
        """Removing any single file -> False."""
        d = self._get_dir("complete_missing")
        paths = _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        for p in paths:
            p.unlink()
            assert _check_fold_complete(d, 0, self.MODEL_NAME) is False
            _make_fake_complete_fold(d, 0, self.MODEL_NAME)

    def test_complete_truncated_pkl(self):
        """Truncated pkl (< _MIN_PKL_BYTES) -> False."""
        d = self._get_dir("complete_truncated")
        paths = _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        # Truncate model pkl
        paths[0].write_bytes(b"x" * 10)
        assert _check_fold_complete(d, 0, self.MODEL_NAME) is False

    def test_complete_empty_dir(self):
        """Empty directory -> False."""
        d = self._get_dir("complete_empty")
        assert _check_fold_complete(d, 0, self.MODEL_NAME) is False

    # --- _check_fold_has_legacy_artifacts ---

    def test_legacy_detection(self):
        """model.pkl + results.json without predictions.pkl -> True."""
        d = self._get_dir("legacy_yes")
        paths = _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        paths[3].unlink()  # Remove predictions.pkl
        assert _check_fold_has_legacy_artifacts(d, 0, self.MODEL_NAME) is True

    def test_legacy_complete_fold_is_not_legacy(self):
        """Complete fold (all 4 files) -> False."""
        d = self._get_dir("legacy_no")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        assert _check_fold_has_legacy_artifacts(d, 0, self.MODEL_NAME) is False

    def test_legacy_only_model_no_results(self):
        """model.pkl without results.json -> False (not legacy)."""
        d = self._get_dir("legacy_partial")
        paths = _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        paths[2].unlink()  # Remove results.json
        paths[3].unlink()  # Remove predictions.pkl
        assert _check_fold_has_legacy_artifacts(d, 0, self.MODEL_NAME) is False

    # --- _save_fold_predictions / _load_fold_results round-trip ---

    def test_save_load_roundtrip(self):
        """Save + load preserves eval_results, raw_preds, and predictions_rows."""
        d = self._get_dir("roundtrip")

        # Write results.json for _load_fold_results
        eval_results = {
            "fold_id": 0, "model_name": self.MODEL_NAME,
            "accuracy": 0.8123, "mcc": 0.6543,
        }
        with open(d / f"fold_0_{self.MODEL_NAME}_results.json", "w") as f:
            json.dump(eval_results, f)

        raw_preds = {
            "y_true": np.array(["A", "B", "C"]),
            "y_pred": np.array(["A", "B", "A"]),
            "y_proba": np.array([[0.7, 0.2, 0.1], [0.1, 0.8, 0.1], [0.5, 0.1, 0.4]]),
            "classes": np.array(["A", "B", "C"]),
        }
        pred_rows = [
            {"specimen_label": "s1", "true_disease": "A"},
            {"specimen_label": "s2", "true_disease": "B"},
            {"specimen_label": "s3", "true_disease": "C"},
        ]

        _save_fold_predictions(
            d, 0, self.MODEL_NAME,
            raw_preds=raw_preds, predictions_rows=pred_rows,
            model_params=self.MODEL_PARAMS,
            training_context=self.TRAINING_CONTEXT,
        )

        loaded_eval, loaded_raw, loaded_rows = _load_fold_results(
            d, 0, self.MODEL_NAME,
        )

        assert loaded_eval == eval_results
        for key in ["y_true", "y_pred", "y_proba", "classes"]:
            np.testing.assert_array_equal(loaded_raw[key], raw_preds[key])
        assert loaded_rows == pred_rows

    # --- _validate_fold_meta ---

    def test_validate_matching_params(self):
        """Matching params pass silently."""
        d = self._get_dir("validate_match")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME,
                                model_params=self.MODEL_PARAMS)
        _validate_fold_meta(
            d, 0, self.MODEL_NAME,
            current_model_params=self.MODEL_PARAMS,
            current_training_context=self.TRAINING_CONTEXT,
        )

    def test_validate_model_name_mismatch(self):
        """model_name mismatch raises ValueError."""
        d = self._get_dir("validate_name")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        # Tamper with _meta
        preds_path = d / f"fold_0_{self.MODEL_NAME}_predictions.pkl"
        with open(preds_path, "rb") as f:
            data = pickle.load(f)
        data["_meta"]["model_name"] = "ridge_cv"
        with open(preds_path, "wb") as f:
            pickle.dump(data, f)

        with pytest.raises(ValueError, match="model_name mismatch"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=self.MODEL_PARAMS,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_training_context_mismatch(self):
        """training_context mismatch raises ValueError."""
        d = self._get_dir("validate_ctx")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME,
                                training_context="cv_single_model")

        with pytest.raises(ValueError, match="training_context mismatch"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=self.MODEL_PARAMS,
                current_training_context="cv_ensemble",
            )

    def test_validate_n_pcs_mismatch(self):
        """n_pcs mismatch raises ValueError."""
        d = self._get_dir("validate_npcs")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME,
                                model_params=self.MODEL_PARAMS)
        different = {**self.MODEL_PARAMS, "n_pcs": 20}

        with pytest.raises(ValueError, match="n_pcs"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=different,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_l1_ratio_mismatch(self):
        """l1_ratio mismatch raises ValueError."""
        d = self._get_dir("validate_l1")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME,
                                model_params=self.MODEL_PARAMS)
        different = {**self.MODEL_PARAMS, "l1_ratio": 0.5}

        with pytest.raises(ValueError, match="l1_ratio"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=different,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_fold_id_mismatch(self):
        """fold_id mismatch raises ValueError."""
        d = self._get_dir("validate_foldid")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        # Tamper: change fold_id in _meta
        preds_path = d / f"fold_0_{self.MODEL_NAME}_predictions.pkl"
        with open(preds_path, "rb") as f:
            data = pickle.load(f)
        data["_meta"]["fold_id"] = 1
        with open(preds_path, "wb") as f:
            pickle.dump(data, f)

        with pytest.raises(ValueError, match="fold_id mismatch"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=self.MODEL_PARAMS,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_missing_meta(self):
        """predictions.pkl without _meta raises ValueError."""
        d = self._get_dir("validate_nometa")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME)
        preds_path = d / f"fold_0_{self.MODEL_NAME}_predictions.pkl"
        data_no_meta = {
            "raw_preds": {"y_true": np.array(["A"]), "y_pred": np.array(["A"]),
                          "y_proba": np.array([[1.0]]), "classes": np.array(["A"])},
            "predictions_rows": [{"specimen_label": "s1"}],
        }
        with open(preds_path, "wb") as f:
            pickle.dump(data_no_meta, f)

        with pytest.raises(ValueError, match="no _meta"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=self.MODEL_PARAMS,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_extra_key_in_current_skips(self):
        """Extra key in current params but not in saved -> skip (backward compat)."""
        d = self._get_dir("validate_extra")
        _make_fake_complete_fold(d, 0, self.MODEL_NAME,
                                model_params=self.MODEL_PARAMS)
        extra = {**self.MODEL_PARAMS, "new_param": "value"}
        # Should not raise
        _validate_fold_meta(
            d, 0, self.MODEL_NAME,
            current_model_params=extra,
            current_training_context=self.TRAINING_CONTEXT,
        )

    def test_validate_run_level_classification_mode_mismatch(self):
        """classification_mode mismatch raises ValueError."""
        d = self._get_dir("validate_mode")
        full_params = {
            **self.MODEL_PARAMS,
            "classification_mode": "multiclass",
            "diseases": None,
            "dataset_name": "mal-id-orig-data",
            "reference_class": None,
            "disease_filter": None,
        }
        _make_fake_complete_fold(d, 0, self.MODEL_NAME, model_params=full_params)
        different = {**full_params, "classification_mode": "binary"}

        with pytest.raises(ValueError, match="classification_mode"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=different,
                current_training_context=self.TRAINING_CONTEXT,
            )

    def test_validate_disease_filter_mismatch(self):
        """disease_filter mismatch raises ValueError."""
        d = self._get_dir("validate_filter")
        full_params = {
            **self.MODEL_PARAMS,
            "disease_filter": None,
        }
        _make_fake_complete_fold(d, 0, self.MODEL_NAME, model_params=full_params)
        different = {**full_params, "disease_filter": ("HIV", "Healthy/Background")}

        with pytest.raises(ValueError, match="disease_filter"):
            _validate_fold_meta(
                d, 0, self.MODEL_NAME,
                current_model_params=different,
                current_training_context=self.TRAINING_CONTEXT,
            )


# ---------------------------------------------------------------------------
# Tier 1: Output path logic
# ---------------------------------------------------------------------------

class TestOutputPathLogic:
    """Tests for get_model_output_dir path construction."""

    def test_cv_single_model_multiclass(self):
        """cv_single_model multiclass path pattern."""
        p = get_model_output_dir(
            "model1", "test-ds", "multiclass", "TCR",
            training_context="cv_single_model",
        )
        parts = p.parts
        assert "cv_single_model" in parts
        assert "model1" in parts
        assert "multiclass" in parts
        assert "TCR" in parts

    def test_cv_ensemble_multiclass(self):
        """cv_ensemble path pattern."""
        p = get_model_output_dir(
            "model1", "test-ds", "multiclass", "TCR",
            training_context="cv_ensemble",
        )
        parts = p.parts
        assert "cv_ensemble" in parts
        assert "base_models" in parts
        assert "model1" in parts
        assert "multiclass" in parts

    def test_binary_and_multi_binary_share_binary_dir(self):
        """Both binary and multi-binary mode_dir is 'binary'."""
        p1 = get_model_output_dir(
            "model1", "ds", "binary", "TCR", training_context="cv_single_model",
        )
        p2 = get_model_output_dir(
            "model1", "ds", "multi-binary", "TCR", training_context="cv_single_model",
        )
        assert p1 == p2

    def test_output_suffix(self):
        """output_suffix appended to mode_dir with double underscore."""
        p = get_model_output_dir(
            "model1", "ds", "multiclass", "TCR",
            training_context="cv_single_model", output_suffix="no_pca",
        )
        assert "multiclass__no_pca" in str(p)

    def test_invalid_training_context_raises(self):
        """Invalid training_context raises ValueError."""
        with pytest.raises(ValueError, match="training_context must be one of"):
            get_model_output_dir(
                "model1", "ds", "multiclass", "TCR",
                training_context="invalid_context",
            )


# ---------------------------------------------------------------------------
# Tier 1: make_pair_name
# ---------------------------------------------------------------------------

class TestMakePairName:
    """Tests for make_pair_name (filesystem-safe pair directory naming)."""

    def test_basic(self):
        assert make_pair_name("HIV", "Healthy/Background") == "HIV_vs_Healthy_Background"

    def test_spaces(self):
        assert make_pair_name("Disease A", "Reference B") == "Disease_A_vs_Reference_B"

    def test_slashes(self):
        assert make_pair_name("A/B", "C\\D") == "A_B_vs_C_D"


# ---------------------------------------------------------------------------
# Tier 1: filter_rare_v_genes
# ---------------------------------------------------------------------------

class TestFilterRareVGenes:
    """Tests for filter_rare_v_genes (training V-gene filtering)."""

    def test_basic_filtering(self):
        """Common V genes are kept, rare ones removed."""
        rng = np.random.RandomState(42)
        n = 1000
        # 10 genes with exponentially decaying frequencies
        genes = [f"TRBV{i}" for i in range(1, 11)]
        weights = np.exp(-np.arange(10) * 0.5)
        weights /= weights.sum()
        seqs = pd.DataFrame({
            V_GENE_COL: rng.choice(genes, size=n, p=weights),
        })

        kept = filter_rare_v_genes(seqs, threshold_quantile=0.5)

        assert isinstance(kept, list)
        assert len(kept) > 0
        assert len(kept) < len(genes)  # Some should be filtered
        # Most common gene should always be kept
        most_common = seqs[V_GENE_COL].value_counts().idxmax()
        assert most_common in kept

    def test_all_equal_frequencies(self):
        """When all V genes have equal frequency, all are kept (median = each freq)."""
        seqs = pd.DataFrame({
            V_GENE_COL: ["TRBV1"] * 100 + ["TRBV2"] * 100 + ["TRBV3"] * 100,
        })
        kept = filter_rare_v_genes(seqs, threshold_quantile=0.5)
        assert len(kept) == 3


# ---------------------------------------------------------------------------
# Tier 2: Integration tests (require test_data/)
# ---------------------------------------------------------------------------

def _has_test_data() -> bool:
    """Check if test data is available."""
    test_data_dir = Path(__file__).parent / "test_data"
    raw_dir = test_data_dir / "raw"
    return (
        test_data_dir.exists()
        and raw_dir.exists()
        and any(raw_dir.glob("part_table_*.tsv.gz"))
    )


def _create_test_loader():
    """Create a test data loader backed by tests/test_data/."""
    from test_helpers import create_test_loader
    return create_test_loader(verbose=0)


# Shared fixture for integration tests
@pytest.fixture(scope="module")
def test_loader():
    """Module-scoped test data loader. Skips if test data unavailable."""
    if not _has_test_data():
        pytest.skip("Test data not available (run scripts/data/create_test_data.py)")
    return _create_test_loader()


@pytest.fixture
def integration_output_dir(request):
    """Per-test output directory, cleaned before each test."""
    test_name = request.node.name
    d = _TEST_OUTPUT_DIR / "integration" / test_name
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True, exist_ok=True)
    return d


# ---------------------------------------------------------------------------
# Integration: Multiclass full pipeline
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestMulticlassPipeline:
    """Integration tests for multiclass training pipeline."""

    def test_train_all_folds_multiclass(self, test_loader, integration_output_dir):
        """Full multiclass pipeline with all 3 folds via train_all_folds."""


        results = train_all_folds(
            fold_ids=[0, 1, 2],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        # Results structure
        assert "multiclass" in results
        mc = results["multiclass"]
        fold_results = mc["fold_results"]
        agg = mc["aggregated_by_model"]["lasso_cv"]

        # All 3 folds trained
        assert len(fold_results) == 3
        assert agg["n_folds"] == 3
        assert agg["n_folds_scored"] == 3

        # Metrics are valid
        assert 0.0 <= agg["accuracy_global"] <= 1.0
        assert agg["confusion_matrix_aggregated"] is not None

        # Per-fold metrics
        for r in fold_results:
            assert r["n_scored"] > 0
            assert r["n_abstained"] == 0
            assert 0.0 <= r["accuracy"] <= 1.0
            assert r["mcc"] is not None

        # Artifacts on disk
        assert any(integration_output_dir.glob("summary_*.json"))
        assert any(integration_output_dir.glob("RESULTS_*.md"))
        for fold_id in [0, 1, 2]:
            assert (integration_output_dir / f"fold_{fold_id}_lasso_cv_model.pkl").exists()
            assert (integration_output_dir / f"fold_{fold_id}_lasso_cv_v_genes.json").exists()
            assert (integration_output_dir / f"fold_{fold_id}_lasso_cv_results.json").exists()
            assert (integration_output_dir / f"fold_{fold_id}_lasso_cv_predictions.pkl").exists()

        # Predictions CSV
        pred_csv = integration_output_dir / "lasso_cv_multiclass_predictions.csv"
        assert pred_csv.exists()
        pred_df = pd.read_csv(pred_csv)
        # Fixed columns
        for col in ["participant_label", "specimen_label", "true_disease",
                     "predicted_disease", "CV_fold"]:
            assert col in pred_df.columns, f"Missing column: {col}"
        # Score columns (one per disease class)
        score_cols = [c for c in pred_df.columns if c.startswith("score_")]
        assert len(score_cols) >= 2, (
            f"Expected at least 2 score_* columns, got {len(score_cols)}: {score_cols}"
        )
        assert len(pred_df) > 0
        # All 3 folds represented
        assert set(pred_df["CV_fold"].unique()) == {0, 1, 2}

    def test_multiclass_fold_ids_none_autodetect(self, test_loader, integration_output_dir):
        """fold_ids=None auto-detects all folds from metadata."""


        results = train_all_folds(
            fold_ids=None,
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        mc = results["multiclass"]
        assert len(mc["fold_results"]) == 3


# ---------------------------------------------------------------------------
# Integration: Binary pipeline
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestBinaryPipeline:
    """Integration tests for binary training pipeline."""

    def test_binary_single_disease(self, test_loader, integration_output_dir):
        """Binary mode with one disease picked from N-class data."""


        results = train_all_folds(
            fold_ids=[0, 1, 2],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="binary",
            reference_class="Healthy/Background",
            diseases=["HIV"],
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        pair_key = "HIV_vs_Healthy_Background"
        assert pair_key in results
        pair_data = results[pair_key]
        fold_results = pair_data["fold_results"]
        agg = pair_data["aggregated_by_model"]["lasso_cv"]

        assert len(fold_results) == 3
        assert agg["auroc_pooled"] is not None
        assert 0.0 <= agg["auroc_pooled"] <= 1.0
        assert agg["auprc_pooled"] is not None
        assert agg["disease"] == "HIV"
        assert agg["reference_class"] == "Healthy/Background"

        # Per-fold binary metrics
        for r in fold_results:
            assert r["auroc_binary"] is not None
            assert 0.0 <= r["auroc_binary"] <= 1.0
            assert r["auprc_binary"] is not None
            assert r["n_abstained"] == 0

        # Binary predictions CSV
        pair_dir = integration_output_dir / pair_key
        pred_csv = pair_dir / "lasso_cv_binary_predictions.csv"
        assert pred_csv.exists()
        pred_df = pd.read_csv(pred_csv)
        expected_cols = [
            "participant_label", "specimen_label", "disease_label",
            "disease_label_str", "disease_model", "model_score",
            "CV_fold",
        ]
        assert list(pred_df.columns) == expected_cols
        assert set(pred_df["disease_label"].unique()).issubset({0, 1})
        assert pred_df["model_score"].between(0.0, 1.0).all()
        assert (pred_df["disease_model"] == "HIV").all()


# ---------------------------------------------------------------------------
# Integration: Multi-binary pipeline
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestMultiBinaryPipeline:
    """Integration tests for multi-binary training pipeline."""

    def test_multi_binary_two_diseases(self, test_loader, integration_output_dir):
        """Multi-binary with 2 diseases vs Healthy/Background."""


        results = train_all_folds(
            fold_ids=[0, 1, 2],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multi-binary",
            reference_class="Healthy/Background",
            diseases=["Covid19", "HIV"],
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        # Two pair keys
        assert "Covid19_vs_Healthy_Background" in results
        assert "HIV_vs_Healthy_Background" in results

        for pair_key in ["Covid19_vs_Healthy_Background", "HIV_vs_Healthy_Background"]:
            pair_data = results[pair_key]
            agg = pair_data["aggregated_by_model"]["lasso_cv"]
            assert agg["auroc_pooled"] is not None
            assert agg["n_folds"] == 3

            # Per-pair artifacts
            pair_dir = integration_output_dir / pair_key
            assert pair_dir.exists()
            for fold_id in [0, 1, 2]:
                assert (pair_dir / f"fold_{fold_id}_lasso_cv_model.pkl").exists()

            # Per-pair summary and results
            assert any(pair_dir.glob("summary_*.json"))
            assert any(pair_dir.glob("RESULTS_*.md"))

    def test_multi_binary_auto_detect_diseases(self, test_loader, integration_output_dir):
        """Multi-binary with diseases=None auto-trains all non-ref diseases."""


        results = train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multi-binary",
            reference_class="Healthy/Background",
            diseases=None,  # auto-detect: should train HIV, Covid19, T1D
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        # Test data has 4 diseases; 3 non-reference pairs expected
        expected_pairs = {
            "Covid19_vs_Healthy_Background",
            "HIV_vs_Healthy_Background",
            "T1D_vs_Healthy_Background",
        }
        assert set(results.keys()) == expected_pairs, (
            f"Expected pairs {expected_pairs}, got {set(results.keys())}"
        )

        for pair_key in expected_pairs:
            pair_data = results[pair_key]
            agg = pair_data["aggregated_by_model"]["lasso_cv"]
            assert agg["n_folds"] == 1
            assert pair_data["fold_results"][0]["n_scored"] > 0


# ---------------------------------------------------------------------------
# Integration: cv_ensemble context
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestCvEnsembleContext:
    """Integration tests for cv_ensemble training context."""

    def test_cv_ensemble_binary(self, test_loader, integration_output_dir):
        """cv_ensemble training context produces valid results."""


        results = train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="binary",
            reference_class="Healthy/Background",
            diseases=["HIV"],
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_ensemble",
        )

        pair_key = "HIV_vs_Healthy_Background"
        pair_data = results[pair_key]
        fold_results = pair_data["fold_results"]

        assert len(fold_results) == 1
        assert fold_results[0]["n_scored"] > 0
        assert fold_results[0]["n_abstained"] == 0
        assert fold_results[0]["auroc_binary"] is not None


# ---------------------------------------------------------------------------
# Integration: output_suffix
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestOutputSuffix:
    """Integration tests for output_suffix parameter."""

    def test_output_suffix_in_summary(self, test_loader, integration_output_dir):
        """output_suffix appears in summary JSON."""


        results = train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
            output_suffix="test_suffix",
        )

        # Summary JSON should contain the suffix
        summary_files = list(integration_output_dir.glob("summary_*.json"))
        assert len(summary_files) == 1
        with open(summary_files[0]) as f:
            summary = json.load(f)
        assert summary["output_suffix"] == "test_suffix"


# ---------------------------------------------------------------------------
# Integration: Resume
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestResumePipeline:
    """Integration tests for resume support."""

    def test_resume_skips_completed_folds(self, test_loader, integration_output_dir):
        """Original run + resume: metrics match, no retraining."""


        common_kwargs = dict(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        # Original run
        orig_results = train_all_folds(**common_kwargs, resume=False)
        orig_acc = orig_results["multiclass"]["fold_results"][0]["accuracy"]
        orig_mcc = orig_results["multiclass"]["fold_results"][0]["mcc"]

        # Resume run (should skip the completed fold)
        t0 = time.time()
        resume_results = train_all_folds(**common_kwargs, resume=True)
        resume_time = time.time() - t0

        resume_acc = resume_results["multiclass"]["fold_results"][0]["accuracy"]
        resume_mcc = resume_results["multiclass"]["fold_results"][0]["mcc"]

        assert orig_acc == resume_acc, (
            f"Accuracy mismatch: orig={orig_acc}, resume={resume_acc}"
        )
        assert orig_mcc == resume_mcc, (
            f"MCC mismatch: orig={orig_mcc}, resume={resume_mcc}"
        )

    def test_resume_retrains_incomplete_fold(self, test_loader, integration_output_dir):
        """Incomplete fold (missing predictions.pkl) is retrained."""


        common_kwargs = dict(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        # Original run
        orig = train_all_folds(**common_kwargs, resume=False)
        orig_acc = orig["multiclass"]["fold_results"][0]["accuracy"]

        # Remove predictions.pkl to simulate incomplete fold
        preds_path = integration_output_dir / "fold_0_lasso_cv_predictions.pkl"
        assert preds_path.exists()
        preds_path.unlink()

        # Resume should retrain
        resumed = train_all_folds(**common_kwargs, resume=True)
        resume_acc = resumed["multiclass"]["fold_results"][0]["accuracy"]

        # Accuracy should match (deterministic model on same data)
        assert orig_acc == resume_acc

        # Predictions.pkl should be restored
        assert preds_path.exists()

    def test_resume_param_mismatch_raises(self, test_loader, integration_output_dir):
        """Resume with different n_pcs raises ValueError."""


        # Original run with n_pcs=10
        train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
            resume=False,
        )

        # Resume with n_pcs=5 should error
        with pytest.raises(ValueError, match="n_pcs"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="multiclass",
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=5,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
                training_context="cv_single_model",
                resume=True,
            )


# ---------------------------------------------------------------------------
# Integration: PCA n_pcs cap
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestPcaNCap:
    """Integration test for PCA n_pcs capping when n_pcs > n_samples."""

    def test_n_pcs_capped_to_n_samples(self, test_loader, integration_output_dir):
        """n_pcs=1000 (larger than n_samples) is silently capped."""


        # This should not error -- n_pcs is capped inside RepertoireClassifier.fit()
        results = train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=1000,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        mc = results["multiclass"]
        assert len(mc["fold_results"]) == 1
        assert mc["fold_results"][0]["n_scored"] > 0


# ---------------------------------------------------------------------------
# Integration: Model save/load round-trip
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestModelSaveLoad:
    """Integration test for RepertoireClassifier save/load round-trip."""

    def test_save_load_predictions_match(self, test_loader, integration_output_dir):
        """Saved and loaded model produce identical predictions."""

        from malid_lite.dataloader import PreprocessingStage

        loader = _create_test_loader()

        # Load fold 0 train
        train_data, train_meta = loader.get_fold_data(0, "train", PreprocessingStage.DOWNSAMPLED)
        # Get split participants
        train_participants = set(loader.get_split_participants(0, "cv_single_model", ["train_smaller1", "train_smaller2"]))
        mask = train_data["participant_label"].isin(train_participants)
        train_data = train_data[mask].copy()
        train_meta = train_meta[train_meta["participant_label"].isin(train_participants)].copy()

        # Filter rare V genes
        kept_v_genes = filter_rare_v_genes(train_data)
        train_data = train_data[train_data[V_GENE_COL].isin(kept_v_genes)].copy()

        # Train model
        model = RepertoireClassifier(gene_locus="TCR", n_pcs=10, verbose=0)
        X_train = model.extract_features(sequences=train_data, metadata=train_meta)
        meta_aligned = train_meta.set_index("specimen_label").loc[X_train.index]
        y_train = meta_aligned["disease"]
        groups = meta_aligned["participant_label"]
        model.fit(X_train, y_train, groups=groups)

        # Load test data
        test_data, test_meta = loader.get_fold_data(0, "test", PreprocessingStage.DOWNSAMPLED)
        test_data = test_data[test_data[V_GENE_COL].isin(kept_v_genes)].copy()
        X_test = model.extract_features(test_data, test_meta, train_vj_columns=model.train_vj_columns_)

        # Original predictions
        orig_pred = model.predict(X_test)
        orig_proba = model.predict_proba(X_test)

        # Save and load
        model_path = integration_output_dir / "model_roundtrip.pkl"
        model.save(model_path)
        loaded = RepertoireClassifier.load(model_path)

        # Loaded predictions
        loaded_pred = loaded.predict(X_test)
        loaded_proba = loaded.predict_proba(X_test)

        np.testing.assert_array_equal(orig_pred, loaded_pred)
        np.testing.assert_array_almost_equal(orig_proba, loaded_proba)
        assert loaded.is_fitted_ is True
        np.testing.assert_array_equal(model.classes_, loaded.classes_)


# ---------------------------------------------------------------------------
# Integration: Bad argument combinations
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestBadArgCombinations:
    """Integration tests for invalid argument combinations."""

    def test_binary_without_reference_class_raises(self, test_loader, integration_output_dir):
        """Binary mode without reference_class raises ValueError."""


        with pytest.raises(ValueError, match="--reference-class is required"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class=None,
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_binary_4_classes_no_diseases_raises(self, test_loader, integration_output_dir):
        """Binary mode with 4 classes and no --diseases raises ValueError."""


        with pytest.raises(ValueError, match="exactly 2 disease classes"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class="Healthy/Background",
                diseases=None,
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_binary_disease_equals_reference_raises(self, test_loader, integration_output_dir):
        """Binary mode where diseases == reference_class raises ValueError."""


        with pytest.raises(ValueError, match="same as --reference-class"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class="Healthy/Background",
                diseases=["Healthy/Background"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_binary_disease_not_in_data_raises(self, test_loader, integration_output_dir):
        """Binary mode with unknown disease raises ValueError."""


        with pytest.raises(ValueError, match="not found in data"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class="Healthy/Background",
                diseases=["NonexistentDisease"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_multi_binary_diseases_includes_reference_raises(self, test_loader, integration_output_dir):
        """Multi-binary where diseases includes reference_class raises."""


        with pytest.raises(ValueError, match="includes reference class"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="multi-binary",
                reference_class="Healthy/Background",
                diseases=["HIV", "Healthy/Background"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_multi_binary_invalid_disease_raises(self, test_loader, integration_output_dir):
        """Multi-binary with unknown disease raises ValueError."""


        with pytest.raises(ValueError, match="not found in data"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="multi-binary",
                reference_class="Healthy/Background",
                diseases=["FakeDisease"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_multiclass_with_diseases_raises(self, test_loader, integration_output_dir):
        """Multiclass mode does not support --diseases."""


        with pytest.raises(ValueError, match="--diseases is not supported"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="multiclass",
                diseases=["HIV"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_reference_not_in_data_raises(self, test_loader, integration_output_dir):
        """Reference class not in data raises ValueError."""


        with pytest.raises(ValueError, match="not found in data classes"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class="NonexistentClass",
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )

    def test_binary_multiple_diseases_raises(self, test_loader, integration_output_dir):
        """Binary mode with multiple diseases in --diseases raises."""


        with pytest.raises(ValueError, match="exactly one entry"):
            train_all_folds(
                fold_ids=[0],
                metadata_path=None,
                output_dir=integration_output_dir,
                dataset_name="test-data",
                classification_mode="binary",
                reference_class="Healthy/Background",
                diseases=["HIV", "Covid19"],
                model_name="lasso_cv",
                gene_locus="TCR",
                n_pcs=10,
                verbose=0,
                cache_dir=TEST_DATA_DIR,
                data_dir=TEST_RAW_DIR,
            )


# ---------------------------------------------------------------------------
# Integration: Summary JSON structure
# ---------------------------------------------------------------------------

@pytest.mark.integration
class TestSummaryJSON:
    """Integration tests for summary JSON content."""

    def test_summary_json_structure(self, test_loader, integration_output_dir):
        """Summary JSON contains all expected keys."""


        train_all_folds(
            fold_ids=[0],
            metadata_path=None,
            output_dir=integration_output_dir,
            dataset_name="test-data",
            classification_mode="multiclass",
            model_name="lasso_cv",
            gene_locus="TCR",
            n_pcs=10,
            verbose=0,
            cache_dir=TEST_DATA_DIR,
            data_dir=TEST_RAW_DIR,
            training_context="cv_single_model",
        )

        summary_files = list(integration_output_dir.glob("summary_*.json"))
        assert len(summary_files) == 1

        with open(summary_files[0]) as f:
            summary = json.load(f)

        expected_keys = {
            "timestamp", "dataset_name", "training_context",
            "classification_mode", "reference_class", "diseases",
            "model_classes", "gene_locus", "output_suffix",
            "fold_ids", "model_names", "l1_ratio", "n_pcs",
            "dataset_counts", "metadata_filter_info",
            "results_by_pair", "aggregated_by_pair",
        }
        missing = expected_keys - set(summary.keys())
        assert not missing, f"Missing keys in summary JSON: {missing}"
        extra = set(summary.keys()) - expected_keys
        assert not extra, f"Unexpected keys in summary JSON: {extra}"

        assert summary["dataset_name"] == "test-data"
        assert summary["classification_mode"] == "multiclass"
        assert summary["gene_locus"] == "TCR"
        assert summary["n_pcs"] == 10
        assert summary["model_names"] == ["lasso_cv"]
        assert summary["training_context"] == "cv_single_model"
        assert summary["fold_ids"] == [0]
        assert summary["l1_ratio"] == 1.0  # TCR default


# ---------------------------------------------------------------------------
# Entry point for running without pytest
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v", "-s"]))
