"""Validity suite — the newcomer "is my setup working?" check.

A small, curated set of END-TO-END tests on the tests/test_data/ mock dataset that a
new user runs to confirm their install, Python environment, and data format all
work — NOT an exhaustive correctness suite (that is the full `pytest tests/`).

Run it with::

    pytest -m validity                 # full newcomer check (includes the ESM-2 path)
    pytest -m "validity and not slow"   # quick check, no Model 3 / ESM-2 (~2-3 min)

All tests here rely on PRECOMPUTED embeddings in test_data/embeddings/. NOTE: that
directory is gitignored (NOT committed) — on a fresh checkout it is generated by the
`slow` test test_model3_embeddings.py::test_integration_generate_embedding_cache, which
`python tests/run_all_tests.py` runs (in group order) before this suite. Running the
validity tier in isolation on a machine without those embeddings will fail at the
subset-cache step; see PIPELINE_GUIDE.md Section 3.4. Nothing here recomputes ESM-2
except where explicitly marked ``slow``.

What it covers:
1. Environment + data-format sanity (loader reads the bundled data).
2. Core training path (a tiny CV ensemble trains and is marked complete).
3. The cross-dataset workflow END-TO-END (PIPELINE_GUIDE.md Section 10):
   build a folds-0+1 subset cache -> train train_all_ensemble on it ->
   evaluate on the held-out fold 2. This doubles as living documentation of the
   folds-subset recipe.

Output: tests/test_outputs/test_validity/. Expected runtime: ~2-3 min without
`slow`, a few min more with it.
"""

import json
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))
sys.path.insert(0, str(Path(__file__).parent))

from test_helpers import TEST_DATA_DIR, TEST_RAW_DIR, TEST_DISEASES, create_test_loader

from malid_lite.dataloader.base import PreprocessingStage
from malid_lite.evaluation import evaluate_external as ee
from malid_lite.training.training_utils import PROJECT_ROOT

SUBSET_SCRIPT = PROJECT_ROOT / "scripts" / "data" / "create_subset_cache.py"
EMBED = TEST_DATA_DIR / "embeddings"
OUTPUT_DIR = Path(__file__).parent / "test_outputs" / Path(__file__).stem


def _fresh_dir(name: str) -> Path:
    d = OUTPUT_DIR / name
    if d.exists():
        shutil.rmtree(d)
    d.mkdir(parents=True, exist_ok=True)
    return d


def _cleanup_models(ds: str):
    d = PROJECT_ROOT / "trained_models" / ds
    if d.exists():
        shutil.rmtree(d)


def _run_eval(ensemble_dir: Path, out_dir: Path, n_jobs: int, extra=()):
    """Invoke evaluate_external.main() in-process against test_data as the test set."""
    argv = [
        "evaluate_external",
        "--ensemble-dir", str(ensemble_dir),
        "--test-cache-dir", str(TEST_DATA_DIR), "--test-dataset-name", "self",
        "--gene-locus", "TCR", "--output-dir", str(out_dir),
        "--n-jobs", str(n_jobs), "--verbose", "0",
    ] + list(extra)
    old = sys.argv
    try:
        sys.argv = argv
        ee.main()
    finally:
        sys.argv = old


@pytest.mark.integration
@pytest.mark.validity
class TestValidity:
    """See module docstring. Marked integration + validity; the ESM-2 test adds slow."""

    def test_environment_and_data_sanity(self):
        """Loader reads the bundled data and returns the expected classes."""
        loader = create_test_loader()
        seqs, meta = loader.get_all_data(PreprocessingStage.DOWNSAMPLED)
        assert len(seqs) > 0 and len(meta) > 0
        assert set(meta["disease"]) == set(TEST_DISEASES)

    def test_cv_ensemble_smoke(self, n_jobs):
        """A tiny CV ensemble (Model 1) trains and is marked training_complete."""
        ds = "test-validity-cv"
        _cleanup_models(ds)
        try:
            subprocess.run(
                [sys.executable, "-m", "malid_lite.training.train_ensemble",
                 "--training-context", "cv", "--models", "1",
                 "--classification-mode", "multiclass", "--gene-locus", "TCR",
                 "--dataset-name", ds, "--cache-dir", str(TEST_DATA_DIR),
                 "--data-dir", str(TEST_RAW_DIR), "--model1-n-pcs", "10",
                 "--metamodel-cv-n-splits", "2", "--n-jobs", str(n_jobs), "--verbose", "0"],
                check=True, capture_output=True, timeout=600,
            )
            ens = (PROJECT_ROOT / "trained_models" / ds / "cv_ensemble"
                   / "ensemble" / "TCR" / "multiclass")
            assert any(ens.glob("fold_*_ridge_cv_metamodel.joblib")), "no metamodel artifact"
        finally:
            _cleanup_models(ds)

    # ------------------------------------------------------------------ #
    # The cross-dataset recipe (living documentation of PIPELINE_GUIDE §10)
    # ------------------------------------------------------------------ #

    def _build_folds01_subset(self, work: Path) -> Path:
        """Step 1 of the recipe: subset metadata to folds 0+1, then build a
        symlinked subset cache. Returns the subset cache dir."""
        import pandas as pd
        meta = pd.read_csv(TEST_DATA_DIR / "metadata.tsv", sep="\t")
        fold_col = next(
            c for c in ("CV_fold", "malid_cross_validation_fold_id_when_in_test_set")
            if c in meta.columns
        )
        sub = meta[meta[fold_col].astype(int).isin([0, 1])].copy()
        subset_meta = work / "folds01_metadata.tsv"
        sub.to_csv(subset_meta, sep="\t", index=False)

        cache = work / "cache"
        subprocess.run(
            [sys.executable, str(SUBSET_SCRIPT),
             "--ref-cache-dir", str(TEST_DATA_DIR),
             "--metadata-subset", str(subset_meta),
             "--dataset-name", "test-validity-folds01",
             "--output-cache-dir", str(cache), "--symlink"],
            check=True, capture_output=True, timeout=300,
        )
        return cache

    def _train_all_ensemble_on_subset(self, ds: str, cache: Path, models, n_jobs: int) -> Path:
        """Step 2: train a train_all_ensemble on the subset cache. Returns ensemble dir."""
        argv = [
            sys.executable, "-m", "malid_lite.training.train_ensemble",
            "--training-context", "train_all", "--models", *models,
            "--classification-mode", "multiclass", "--gene-locus", "TCR",
            "--dataset-name", ds, "--cache-dir", str(cache),
            "--model1-n-pcs", "10", "--metamodel-cv-n-splits", "2",
            "--n-jobs", str(n_jobs), "--verbose", "0",
        ]
        if "3" in models:
            argv += ["--model3-embedding-dir", str(EMBED)]
        subprocess.run(argv, check=True, capture_output=True, timeout=900)
        return (PROJECT_ROOT / "trained_models" / ds / "train_all_ensemble"
                / "ensemble" / "TCR" / "multiclass")

    def _assert_eval_outputs(self, out: Path, expect_model3: bool):
        """Step 3 checks: metrics + report + predictions produced on the held-out fold."""
        results = json.loads(next(out.glob("results_*.json")).read_text())
        assert results["ensemble"] is not None
        # test_data fold 2 has 24 specimens; the model never saw them.
        assert results["n_test_specimens"] == 24
        assert any(out.glob("RESULTS_*.md"))
        assert any(out.glob("predictions_*.csv"))
        assert (out / "figures").is_dir() and any((out / "figures").glob("*.png"))
        if expect_model3:
            assert "model3" in results["base_models"]

    def test_folds_subset_train_eval_recipe(self, n_jobs):
        """Full cross-dataset recipe (Model 1): subset cache -> train-all ensemble
        -> evaluate on the held-out fold 2."""
        ds = "test-validity-folds01"
        _cleanup_models(ds)
        work = _fresh_dir("recipe_m1")
        try:
            cache = self._build_folds01_subset(work)
            ens = self._train_all_ensemble_on_subset(ds, cache, ("1",), n_jobs)
            out = work / "eval_fold2"
            _run_eval(ens, out, n_jobs, extra=["--test-on-folds", "2"])
            self._assert_eval_outputs(out, expect_model3=False)
        finally:
            _cleanup_models(ds)

    @pytest.mark.slow
    def test_folds_subset_recipe_with_model3(self, n_jobs):
        """Same recipe including Model 3 (ESM-2), using PRECOMPUTED embeddings —
        validates the full ensemble + embedding path. Marked slow."""
        ds = "test-validity-folds01-m3"
        _cleanup_models(ds)
        work = _fresh_dir("recipe_m13")
        try:
            cache = self._build_folds01_subset(work)
            ens = self._train_all_ensemble_on_subset(ds, cache, ("1", "3"), n_jobs)
            out = work / "eval_fold2"
            _run_eval(ens, out, n_jobs, extra=["--test-on-folds", "2",
                                               "--test-embedding-dir", str(EMBED)])
            self._assert_eval_outputs(out, expect_model3=True)
        finally:
            _cleanup_models(ds)
