#!/usr/bin/env python
"""Merge participant and embedding cache files from two separate source caches into one.

This script builds a unified Mal-ID-Lite cache by copying (or symlinking) per-participant
cache files from two independent source caches into a single output cache directory.
The result is a cache that the pipeline can use directly for training (train_ensemble.py)
without rebuilding participant caches or recomputing embeddings.

The script determines which source cache to use for each participant by reading a
"data-origin" column (or any user-specified column) from the metadata file. Each unique
value in that column is mapped to a source cache directory via --source arguments.

What gets created in the output directory:
  - participants/{label}_clean.parquet       (Stage 1 preprocessed sequences)
  - participants/{label}_stats.json          (preprocessing statistics)
  - metadata.tsv                             (tab-separated metadata for the loader)
  - metadata_processed.tsv                   (same content -- loader uses this on subsequent runs)

What gets created in the output embedding directory (default: <output-cache-dir>/embeddings/):
  - {label}_embeddings.npy                   (ESM-2 sequence embeddings)
  - {label}_downsampled.parquet              (downsampled sequences matching embeddings)
  - {label}_stats.json                       (embedding statistics)

What is NOT created (auto-generated by the pipeline at training time):
  - data_folds/    (fold-level sequence data)
  - splits/        (train/test split definitions)
  - reports/       (data quality reports)

Arguments
---------
--metadata PATH  (required)
    Path to the united metadata file (CSV or TSV). Must contain columns:
    participant_label, specimen_label, disease, CV_fold (or legacy name
    malid_cross_validation_fold_id_when_in_test_set), and the origin column
    (see --origin-column). Separator is auto-detected from file extension:
    .csv -> comma, .tsv -> tab.

--origin-column NAME  (required)
    Name of the metadata column that identifies which source cache a
    participant belongs to. Each unique value in this column must have a
    corresponding --source argument.

--source NAME=PATH  (required, repeatable)
    Maps a value from the origin column to a source cache directory.
    Format: VALUE=PATH where VALUE is one of the unique values in the
    origin column and PATH is the directory containing participants/ and
    embeddings/ subdirectories. Must provide exactly one --source for each
    unique value in the origin column.

    Example:
        --source external-dataset=/path/to/T1D_external_only
        --source mal-id-dataset=/path/to/mal-id-orig-data

--output-cache-dir PATH  (required)
    Output directory for the merged cache. The script creates participants/
    subdirectory here, along with metadata.tsv and metadata_processed.tsv.

--source-embedding-dir NAME=PATH  (optional, repeatable)
    Override the embedding directory for a specific source. By default,
    embeddings are read from <source-cache-dir>/embeddings/ for each source.
    Use when source embeddings were written to a custom location (e.g., via
    compute_model3_embeddings.py --output-embedding-dir).

    Example:
        --source-embedding-dir external-dataset=/fast-storage/external-embeddings

--output-embedding-dir PATH  (optional)
    Output directory for merged embeddings. If omitted, defaults to
    <output-cache-dir>/embeddings/. Use to write merged embeddings to a
    custom location separate from the cache directory.

--symlink  (optional, default: off)
    Create symbolic links to source files instead of copying them. Much
    faster and saves disk space, but the merged cache becomes dependent on
    the source caches remaining in place and unchanged.

--overwrite  (optional, default: off)
    If cache artifacts already exist in the output directory (participants/,
    embeddings/, metadata.tsv, metadata_processed.tsv), delete them before
    writing. Without this flag, the script errors if any of these exist.
    When --output-embedding-dir is external, also deletes that directory
    if it already exists.
    The input --metadata file must not reside at output-cache-dir/metadata.tsv
    or output-cache-dir/metadata_processed.tsv (the script errors upfront
    if it does, since those paths are output artifacts).

Usage
-----
    # Basic usage with two source caches:
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united

    # With symlinks (saves disk space, faster):
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united \\
        --symlink

    # With custom embedding directories:
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/cache_a \\
        --source mal-id-dataset=/path/to/cache_b \\
        --source-embedding-dir external-dataset=/fast-storage/ext-embeddings \\
        --output-cache-dir /path/to/T1D_united \\
        --output-embedding-dir /fast-storage/united-embeddings

    # Overwrite previous merge:
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united \\
        --overwrite

    # After creating the merged cache, train with:
    python malid_lite/training/train_ensemble.py \\
        --metadata-path /path/to/T1D_united/metadata_processed.tsv \\
        --cache-dir /path/to/T1D_united \\
        --dataset-name T1D_united \\
        --classification-mode multiclass
"""

import argparse
import os
import shutil
import sys
import tempfile
from pathlib import Path

import pandas as pd

FOLD_COL = "CV_fold"
_LEGACY_FOLD_COL = "malid_cross_validation_fold_id_when_in_test_set"

REQUIRED_METADATA_COLS = [
    "participant_label",
    "specimen_label",
    "disease",
    FOLD_COL,
]

# Per-participant filename patterns (without subdirectory prefix).
# The subdirectory (participants/ or embedding dir) is resolved at runtime
# so that embedding files can live in a custom directory.
# Note: "{label}_stats.json" appears in both lists — they are different files
# in different directories (preprocessing stats vs embedding stats).
PARTICIPANT_FILE_PATTERNS = [
    "{label}_clean.parquet",
    "{label}_stats.json",
]
EMBEDDING_FILE_PATTERNS = [
    "{label}_embeddings.npy",
    "{label}_downsampled.parquet",
    "{label}_stats.json",
]

# Artifacts the script writes into the output directory.
# --overwrite deletes exactly these (not the whole directory).
OUTPUT_ARTIFACTS = ["participants", "embeddings", "metadata.tsv", "metadata_processed.tsv"]


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Merge participant and embedding cache files from two separate source "
            "caches into a single unified cache for Mal-ID-Lite training."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/cache_tools/merge_caches.py \\\n"
            "      --metadata data/metadata_united.csv \\\n"
            "      --origin-column data-origin \\\n"
            "      --source external-dataset=/path/to/cache_a \\\n"
            "      --source mal-id-dataset=/path/to/cache_b \\\n"
            "      --output-cache-dir /path/to/merged_cache\n\n"
            "  # With symlinks:\n"
            "  python scripts/cache_tools/merge_caches.py \\\n"
            "      --metadata data/metadata_united.csv \\\n"
            "      --origin-column data-origin \\\n"
            "      --source external-dataset=/path/to/cache_a \\\n"
            "      --source mal-id-dataset=/path/to/cache_b \\\n"
            "      --output-cache-dir /path/to/merged_cache \\\n"
            "      --symlink\n\n"
            "  # With custom embedding directories:\n"
            "  python scripts/cache_tools/merge_caches.py \\\n"
            "      --metadata data/metadata_united.csv \\\n"
            "      --origin-column data-origin \\\n"
            "      --source external-dataset=/path/to/cache_a \\\n"
            "      --source mal-id-dataset=/path/to/cache_b \\\n"
            "      --source-embedding-dir external-dataset=/fast-storage/ext-emb \\\n"
            "      --output-cache-dir /path/to/merged_cache \\\n"
            "      --output-embedding-dir /fast-storage/merged-emb\n"
        ),
    )

    parser.add_argument(
        "--metadata",
        type=Path,
        required=True,
        help="Path to the united metadata file (CSV or TSV, auto-detected from extension).",
    )
    parser.add_argument(
        "--origin-column",
        type=str,
        required=True,
        help=(
            "Metadata column that identifies which source cache each participant "
            "belongs to. Each unique value must have a corresponding --source."
        ),
    )
    parser.add_argument(
        "--source",
        type=str,
        action="append",
        required=True,
        dest="sources",
        metavar="NAME=PATH",
        help=(
            "Map an origin-column value to a source cache directory. "
            "Format: VALUE=PATH. Repeatable — provide one per unique origin value."
        ),
    )
    parser.add_argument(
        "--output-cache-dir",
        type=Path,
        required=True,
        help="Output directory for the merged cache.",
    )
    parser.add_argument(
        "--source-embedding-dir",
        type=str,
        action="append",
        dest="source_embedding_dirs",
        metavar="NAME=PATH",
        help=(
            "Override embedding directory for a source. Format: NAME=PATH where "
            "NAME matches a --source name. Default: <source-cache-dir>/embeddings/. "
            "Repeatable — provide one per source that uses a custom embedding location."
        ),
    )
    parser.add_argument(
        "--output-embedding-dir",
        type=Path,
        default=None,
        help=(
            "Output embedding directory. Default: <output-cache-dir>/embeddings/. "
            "Use to write merged embeddings to a custom location."
        ),
    )
    parser.add_argument(
        "--symlink",
        action="store_true",
        help="Create symbolic links instead of copying files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help=(
            "Delete existing cache artifacts in the output directory before writing. "
            "Only removes participants/, embeddings/, metadata.tsv, metadata_processed.tsv."
        ),
    )

    return parser.parse_args()


def parse_source_args(source_args):
    """Parse --source NAME=PATH arguments into a dict.

    Parameters
    ----------
    source_args : list[str]
        Raw --source argument values, each in "NAME=PATH" format.

    Returns
    -------
    dict[str, Path]
        Mapping from origin value to source cache directory path.
    """
    source_map = {}
    for arg in source_args:
        if "=" not in arg:
            print(
                f"Error: --source argument must be in NAME=PATH format, got: '{arg}'",
                file=sys.stderr,
            )
            sys.exit(1)

        # Split on first '=' only (paths may contain '=' in theory)
        name, path_str = arg.split("=", 1)
        name = name.strip()
        path_str = path_str.strip()

        if not name:
            print(f"Error: empty name in --source argument: '{arg}'", file=sys.stderr)
            sys.exit(1)
        if not path_str:
            print(f"Error: empty path in --source argument: '{arg}'", file=sys.stderr)
            sys.exit(1)

        if name in source_map:
            print(
                f"Error: duplicate --source name '{name}'. "
                f"Each origin value should appear exactly once.",
                file=sys.stderr,
            )
            sys.exit(1)

        source_path = Path(path_str).resolve()
        if not source_path.is_dir():
            print(
                f"Error: source cache directory does not exist: {source_path}\n"
                f"  (from --source {name}={path_str})",
                file=sys.stderr,
            )
            sys.exit(1)

        # Check for two different names pointing to the same directory
        for existing_name, existing_path in source_map.items():
            if source_path == existing_path:
                print(
                    f"Error: --source '{name}' and --source '{existing_name}' both "
                    f"point to the same directory: {source_path}",
                    file=sys.stderr,
                )
                sys.exit(1)

        source_map[name] = source_path

    return source_map


def parse_source_embedding_args(source_embedding_args, source_map):
    """Parse --source-embedding-dir NAME=PATH arguments into a dict.

    Validates that each NAME matches an existing --source name and that
    the directory exists.

    Parameters
    ----------
    source_embedding_args : list[str] or None
        Raw --source-embedding-dir argument values, each in "NAME=PATH" format.
        None if the flag was never used.
    source_map : dict[str, Path]
        The parsed --source mapping (for validating names).

    Returns
    -------
    dict[str, Path]
        Mapping from source name to embedding directory. Only includes
        entries for sources with explicit overrides.
    """
    if not source_embedding_args:
        return {}

    embedding_map = {}
    for arg in source_embedding_args:
        if "=" not in arg:
            print(
                f"Error: --source-embedding-dir argument must be in NAME=PATH format, "
                f"got: '{arg}'",
                file=sys.stderr,
            )
            sys.exit(1)

        name, path_str = arg.split("=", 1)
        name = name.strip()
        path_str = path_str.strip()

        if not name:
            print(
                f"Error: empty name in --source-embedding-dir argument: '{arg}'",
                file=sys.stderr,
            )
            sys.exit(1)
        if not path_str:
            print(
                f"Error: empty path in --source-embedding-dir argument: '{arg}'",
                file=sys.stderr,
            )
            sys.exit(1)

        if name not in source_map:
            print(
                f"Error: --source-embedding-dir name '{name}' does not match any "
                f"--source name.\n"
                f"  Available --source names: {sorted(source_map.keys())}",
                file=sys.stderr,
            )
            sys.exit(1)

        if name in embedding_map:
            print(
                f"Error: duplicate --source-embedding-dir name '{name}'.",
                file=sys.stderr,
            )
            sys.exit(1)

        emb_path = Path(path_str).resolve()
        if not emb_path.is_dir():
            print(
                f"Error: source embedding directory does not exist: {emb_path}\n"
                f"  (from --source-embedding-dir {name}={path_str})",
                file=sys.stderr,
            )
            sys.exit(1)

        # Check for two different names pointing to the same directory
        for existing_name, existing_path in embedding_map.items():
            if emb_path == existing_path:
                print(
                    f"Error: --source-embedding-dir '{name}' and "
                    f"--source-embedding-dir '{existing_name}' both "
                    f"point to the same directory: {emb_path}",
                    file=sys.stderr,
                )
                sys.exit(1)

        embedding_map[name] = emb_path

    return embedding_map


def build_source_embedding_map(source_map, source_embedding_overrides):
    """Build a complete source-name -> embedding-dir mapping.

    For sources without an explicit override, defaults to
    source_cache_dir / "embeddings".

    Parameters
    ----------
    source_map : dict[str, Path]
        Origin value -> source cache directory.
    source_embedding_overrides : dict[str, Path]
        Explicit embedding dir overrides from --source-embedding-dir.

    Returns
    -------
    dict[str, Path]
        Complete mapping: source name -> embedding directory.
    """
    result = {}
    for name, cache_dir in source_map.items():
        if name in source_embedding_overrides:
            result[name] = source_embedding_overrides[name]
        else:
            result[name] = cache_dir / "embeddings"
    return result


def detect_separator(metadata_path):
    """Detect CSV/TSV separator from file extension.

    Parameters
    ----------
    metadata_path : Path
        Path to the metadata file.

    Returns
    -------
    str
        ',' for .csv, '\\t' for .tsv.
    """
    ext = metadata_path.suffix.lower()
    if ext == ".csv":
        return ","
    elif ext == ".tsv":
        return "\t"
    else:
        print(
            f"Error: cannot auto-detect separator for extension '{ext}'. "
            f"Rename the metadata file to .csv or .tsv.",
            file=sys.stderr,
        )
        sys.exit(1)


def load_and_validate_metadata(metadata_path, origin_column, source_map):
    """Load metadata, validate required columns and origin-to-source mapping.

    Parameters
    ----------
    metadata_path : Path
        Path to the metadata file.
    origin_column : str
        Column name that identifies which source cache each participant belongs to.
    source_map : dict[str, Path]
        Mapping from origin-column values to source cache directories.

    Returns
    -------
    pd.DataFrame
        Validated metadata with CV_fold column (legacy name normalized).
    """
    if not metadata_path.is_file():
        print(f"Error: metadata file not found: {metadata_path}", file=sys.stderr)
        sys.exit(1)

    sep = detect_separator(metadata_path)
    metadata = pd.read_csv(metadata_path, sep=sep)

    if metadata.empty:
        print(f"Error: metadata file has no data rows: {metadata_path}", file=sys.stderr)
        sys.exit(1)

    # Normalize legacy fold column name
    if _LEGACY_FOLD_COL in metadata.columns and FOLD_COL not in metadata.columns:
        metadata = metadata.rename(columns={_LEGACY_FOLD_COL: FOLD_COL})

    # Check required columns
    missing_cols = [c for c in REQUIRED_METADATA_COLS if c not in metadata.columns]
    if missing_cols:
        print(
            f"Error: metadata is missing required columns: {missing_cols}\n"
            f"  Required: {REQUIRED_METADATA_COLS}\n"
            f"  Found: {list(metadata.columns)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check origin column exists
    if origin_column not in metadata.columns:
        print(
            f"Error: origin column '{origin_column}' not found in metadata.\n"
            f"  Available columns: {list(metadata.columns)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check for NaN in critical columns
    for col in ["participant_label", "specimen_label", "disease", FOLD_COL, origin_column]:
        n_nan = metadata[col].isna().sum()
        if n_nan > 0:
            print(
                f"Error: metadata has {n_nan} NaN value(s) in column '{col}'.",
                file=sys.stderr,
            )
            sys.exit(1)

    # Validate origin column values match --source arguments exactly
    origin_values = set(metadata[origin_column].unique())
    source_names = set(source_map.keys())

    missing_sources = origin_values - source_names
    if missing_sources:
        print(
            f"Error: origin column '{origin_column}' has values with no --source mapping:\n"
            f"  Missing: {sorted(missing_sources)}\n"
            f"  Provided --source names: {sorted(source_names)}",
            file=sys.stderr,
        )
        sys.exit(1)

    unused_sources = source_names - origin_values
    if unused_sources:
        print(
            f"Error: --source name(s) not found in origin column '{origin_column}':\n"
            f"  Unused: {sorted(unused_sources)}\n"
            f"  Origin values in metadata: {sorted(origin_values)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check for duplicate specimen labels
    if metadata["specimen_label"].duplicated().any():
        dupes = metadata["specimen_label"][metadata["specimen_label"].duplicated()].tolist()
        print(
            f"Error: metadata has duplicate specimen_labels: {dupes[:10]}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check that each participant maps to exactly one origin
    participant_origins = metadata.groupby("participant_label")[origin_column].nunique()
    multi_origin = participant_origins[participant_origins > 1]
    if len(multi_origin) > 0:
        print(
            f"Error: {len(multi_origin)} participant(s) appear in multiple origins:\n"
            f"  {multi_origin.index.tolist()[:10]}",
            file=sys.stderr,
        )
        sys.exit(1)

    return metadata


def _build_participant_map(metadata, origin_column, mapping_dict):
    """Build a mapping from each participant label to a value via the origin column.

    Generic helper used by both source-cache and embedding-dir mappings.

    Parameters
    ----------
    metadata : pd.DataFrame
        Validated metadata.
    origin_column : str
        Column identifying the source.
    mapping_dict : dict[str, Path]
        Origin value -> directory path.

    Returns
    -------
    dict[str, Path]
        participant_label -> directory path.
    """
    # One row per participant (take first row for multi-specimen participants)
    participant_origin = (
        metadata.drop_duplicates(subset="participant_label")
        .set_index("participant_label")[origin_column]
    )
    return {
        str(label): mapping_dict[origin]
        for label, origin in participant_origin.items()
    }


def build_participant_source_map(metadata, origin_column, source_map):
    """Build a mapping from each participant label to its source cache directory.

    Parameters
    ----------
    metadata : pd.DataFrame
        Validated metadata.
    origin_column : str
        Column identifying the source.
    source_map : dict[str, Path]
        Origin value -> source cache directory.

    Returns
    -------
    dict[str, Path]
        participant_label -> source cache directory.
    """
    return _build_participant_map(metadata, origin_column, source_map)


def build_participant_embedding_map(metadata, origin_column, source_embedding_map):
    """Build a mapping from each participant label to its source embedding directory.

    Parameters
    ----------
    metadata : pd.DataFrame
        Validated metadata.
    origin_column : str
        Column identifying the source.
    source_embedding_map : dict[str, Path]
        Origin value -> source embedding directory.

    Returns
    -------
    dict[str, Path]
        participant_label -> source embedding directory.
    """
    return _build_participant_map(metadata, origin_column, source_embedding_map)


def validate_source_files(participant_source_map, participant_embedding_map):
    """Verify all required cache files exist in the source caches.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        participant_label -> source cache directory (for participant files).
    participant_embedding_map : dict[str, Path]
        participant_label -> source embedding directory (for embedding files).

    Returns
    -------
    list[str]
        List of error messages (empty if all files found).
    """
    missing = []
    for label in sorted(participant_source_map.keys()):
        source_dir = participant_source_map[label]
        participants_dir = source_dir / "participants"

        for pattern in PARTICIPANT_FILE_PATTERNS:
            file_path = participants_dir / pattern.format(label=label)
            if not file_path.exists():
                missing.append(
                    f"  participants/{pattern.format(label=label)}  "
                    f"(source: {source_dir.name})"
                )

        embedding_dir = participant_embedding_map[label]
        for pattern in EMBEDDING_FILE_PATTERNS:
            file_path = embedding_dir / pattern.format(label=label)
            if not file_path.exists():
                missing.append(
                    f"  {embedding_dir.name}/{pattern.format(label=label)}  "
                    f"(source embedding dir: {embedding_dir})"
                )

    return missing


def handle_existing_artifacts(output_cache_dir, output_embedding_dir, overwrite):
    """Check for existing artifacts and handle according to --overwrite flag.

    Checks both the output cache directory (participants/, metadata files) and
    the output embedding directory. When output_embedding_dir is external
    (not inside output_cache_dir), it is checked separately.

    Parameters
    ----------
    output_cache_dir : Path
        Output cache directory.
    output_embedding_dir : Path
        Output embedding directory.
    overwrite : bool
        If True, delete existing artifacts. If False, error on conflict.
    """
    existing = []

    # Check standard artifacts in output_cache_dir
    for name in OUTPUT_ARTIFACTS:
        path = output_cache_dir / name
        if path.exists():
            existing.append(("cache", name, path))

    # Check external embedding dir (if different from default)
    embedding_is_external = (output_embedding_dir != output_cache_dir / "embeddings")
    if embedding_is_external and output_embedding_dir.exists():
        existing.append(("embedding", str(output_embedding_dir), output_embedding_dir))

    if not existing:
        return

    if not overwrite:
        lines = []
        for loc_type, name, _ in existing:
            if loc_type == "cache":
                lines.append(f"  - {name}")
            else:
                lines.append(f"  - (external embedding dir) {name}")
        print(
            f"Error: output already contains cache artifacts:\n"
            + "\n".join(lines)
            + "\n\n  Use --overwrite to delete them and recreate.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"  --overwrite: removing existing artifacts...")
    for loc_type, name, path in existing:
        if path.is_dir():
            shutil.rmtree(path)
            if loc_type == "cache":
                print(f"    Removed directory: {name}/")
            else:
                print(f"    Removed external embedding directory: {path}")
        else:
            path.unlink()
            print(f"    Removed file: {name}")


def copy_or_link_files(
    participant_source_map,
    participant_embedding_map,
    output_cache_dir,
    output_embedding_dir,
    use_symlinks,
):
    """Copy (or symlink) all participant and embedding files to the output cache.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        participant_label -> source cache directory (for participant files).
    participant_embedding_map : dict[str, Path]
        participant_label -> source embedding directory (for embedding files).
    output_cache_dir : Path
        Destination cache directory (participants/ created inside).
    output_embedding_dir : Path
        Destination embedding directory.
    use_symlinks : bool
        If True, create symbolic links instead of copies.

    Returns
    -------
    dict
        Summary: n_files, total_bytes, n_participants.
    """
    output_participants_dir = output_cache_dir / "participants"
    output_participants_dir.mkdir(parents=True, exist_ok=True)
    output_embedding_dir.mkdir(parents=True, exist_ok=True)

    n_files = 0
    total_bytes = 0
    action = "Linking" if use_symlinks else "Copying"

    sorted_participants = sorted(participant_source_map.keys())
    n_total = len(sorted_participants)

    for idx, label in enumerate(sorted_participants, 1):
        if idx == 1 or idx == n_total or idx % 50 == 0:
            print(f"  {action} {idx}/{n_total}: {label}")

        source_dir = participant_source_map[label]
        source_participants_dir = source_dir / "participants"
        source_embedding_dir = participant_embedding_map[label]

        # Participant files
        for pattern in PARTICIPANT_FILE_PATTERNS:
            src = source_participants_dir / pattern.format(label=label)
            dst = output_participants_dir / pattern.format(label=label)

            if use_symlinks:
                dst.symlink_to(src.resolve())
            else:
                shutil.copy2(src, dst)

            n_files += 1
            total_bytes += src.stat().st_size

        # Embedding files
        for pattern in EMBEDDING_FILE_PATTERNS:
            src = source_embedding_dir / pattern.format(label=label)
            dst = output_embedding_dir / pattern.format(label=label)

            if use_symlinks:
                dst.symlink_to(src.resolve())
            else:
                shutil.copy2(src, dst)

            n_files += 1
            total_bytes += src.stat().st_size

    return {
        "n_files": n_files,
        "total_bytes": total_bytes,
        "n_participants": n_total,
    }


def save_metadata_tsv(metadata, output_cache_dir):
    """Save metadata as metadata.tsv and metadata_processed.tsv (tab-separated).

    Uses atomic writes (write to temp file, then rename) to prevent corruption.

    Parameters
    ----------
    metadata : pd.DataFrame
        The united metadata to save.
    output_cache_dir : Path
        Destination cache directory.
    """
    for filename in ("metadata.tsv", "metadata_processed.tsv"):
        target = output_cache_dir / filename
        fd, tmp_path = tempfile.mkstemp(dir=output_cache_dir, suffix=".tsv")
        try:
            os.close(fd)
            metadata.to_csv(tmp_path, sep="\t", index=False)
            os.rename(tmp_path, target)
        except Exception:
            if Path(tmp_path).exists():
                os.unlink(tmp_path)
            raise


def validate_output(
    participant_source_map,
    output_cache_dir,
    output_embedding_dir,
    use_symlinks,
):
    """Validate that all expected files exist in the output cache.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        Expected participant labels and their sources.
    output_cache_dir : Path
        Output cache directory (contains participants/).
    output_embedding_dir : Path
        Output embedding directory.
    use_symlinks : bool
        If True, also verify symlinks are not broken.

    Returns
    -------
    list[str]
        List of error messages (empty if all valid).
    """
    errors = []
    output_participants_dir = output_cache_dir / "participants"

    # Check metadata files
    for filename in ("metadata.tsv", "metadata_processed.tsv"):
        path = output_cache_dir / filename
        if not path.exists():
            errors.append(f"Missing: {filename}")
        elif path.stat().st_size == 0:
            errors.append(f"Empty: {filename}")

    # Check per-participant files
    for label in sorted(participant_source_map.keys()):
        for pattern in PARTICIPANT_FILE_PATTERNS:
            rel_path = f"participants/{pattern.format(label=label)}"
            file_path = output_participants_dir / pattern.format(label=label)
            if not file_path.exists():
                errors.append(f"Missing: {rel_path}")
            else:
                if use_symlinks and file_path.is_symlink():
                    if not file_path.resolve().exists():
                        errors.append(f"Broken symlink: {rel_path}")
                        continue
                if file_path.stat().st_size == 0:
                    errors.append(f"Empty file: {rel_path}")

        for pattern in EMBEDDING_FILE_PATTERNS:
            filename = pattern.format(label=label)
            file_path = output_embedding_dir / filename
            if not file_path.exists():
                errors.append(f"Missing: {output_embedding_dir.name}/{filename}")
            else:
                if use_symlinks and file_path.is_symlink():
                    if not file_path.resolve().exists():
                        errors.append(f"Broken symlink: {output_embedding_dir.name}/{filename}")
                        continue
                if file_path.stat().st_size == 0:
                    errors.append(f"Empty file: {output_embedding_dir.name}/{filename}")

    return errors


def format_size(bytes_size):
    """Format bytes to human-readable size string."""
    for unit in ["B", "KB", "MB", "GB"]:
        if bytes_size < 1024:
            return f"{bytes_size:.1f} {unit}"
        bytes_size /= 1024
    return f"{bytes_size:.1f} TB"


def print_summary(metadata, origin_column, source_map):
    """Print a summary of the merged cache contents.

    Parameters
    ----------
    metadata : pd.DataFrame
        The united metadata.
    origin_column : str
        Column identifying the source.
    source_map : dict[str, Path]
        Origin value -> source cache directory.
    """
    participants_df = metadata.drop_duplicates(subset="participant_label")
    diseases = sorted(metadata["disease"].unique())
    folds = sorted(int(f) for f in metadata[FOLD_COL].unique())

    print(f"\n{'=' * 65}")
    print("  MERGED CACHE SUMMARY")
    print(f"{'=' * 65}")
    print(f"  Participants: {len(participants_df)}")
    print(f"  Specimens:    {metadata['specimen_label'].nunique()}")
    print(f"  Diseases:     {len(diseases)} -- {diseases}")
    print(f"  Folds:        {len(folds)} -- {folds}")

    # Per-source breakdown
    print(f"\n  Per source:")
    for origin_value in sorted(source_map.keys()):
        origin_mask = metadata[origin_column] == origin_value
        origin_participants = metadata.loc[origin_mask, "participant_label"].nunique()
        origin_specimens = origin_mask.sum()
        print(
            f"    {origin_value}: "
            f"{origin_participants} participants, {origin_specimens} specimens "
            f"(from {source_map[origin_value]})"
        )

    # Per-fold, per-disease breakdown
    print(f"\n  {'Fold':<6} {'Participants':<14} ", end="")
    for d in diseases:
        label = d[:18] if len(d) > 18 else d
        print(f"{label:<20} ", end="")
    print()
    print(f"  {'-' * 6} {'-' * 14} ", end="")
    for _ in diseases:
        print(f"{'-' * 20} ", end="")
    print()

    for fold_id in folds:
        fold_parts = participants_df[participants_df[FOLD_COL] == fold_id]
        print(f"  {fold_id:<6} {len(fold_parts):<14} ", end="")
        for d in diseases:
            n = (fold_parts["disease"] == d).sum()
            print(f"{n:<20} ", end="")
        print()

    print(f"  {'-' * 6} {'-' * 14} ", end="")
    for _ in diseases:
        print(f"{'-' * 20} ", end="")
    print()
    print(f"  {'Total':<6} {len(participants_df):<14} ", end="")
    for d in diseases:
        n = (participants_df["disease"] == d).sum()
        print(f"{n:<20} ", end="")
    print()
    print()


def main():
    args = parse_args()

    metadata_path = args.metadata.resolve()
    output_cache_dir = args.output_cache_dir.resolve()
    output_embedding_dir = (
        args.output_embedding_dir.resolve()
        if args.output_embedding_dir is not None
        else output_cache_dir / "embeddings"
    )

    # --- Check input metadata won't be overwritten by output artifacts ---
    # The script writes metadata.tsv and metadata_processed.tsv into
    # output_cache_dir. If the input --metadata file is at one of those
    # paths, --overwrite would delete the input before it can be re-saved.
    output_metadata_paths = [
        output_cache_dir / "metadata.tsv",
        output_cache_dir / "metadata_processed.tsv",
    ]
    if metadata_path in output_metadata_paths:
        print(
            f"Error: input --metadata file would be overwritten by output:\n"
            f"  --metadata:       {metadata_path}\n"
            f"  --output-cache-dir: {output_cache_dir}\n"
            f"  The script writes metadata.tsv and metadata_processed.tsv into "
            f"the output directory.\n"
            f"  Move the input metadata file to a different location, or use a "
            f"different --output-cache-dir.",
            file=sys.stderr,
        )
        sys.exit(1)

    # --- Step 1: Parse --source arguments ---
    print("Step 1: Parsing source arguments...")
    source_map = parse_source_args(args.sources)
    for name, path in sorted(source_map.items()):
        print(f"  {name} -> {path}")

    # --- Step 1b: Parse --source-embedding-dir arguments ---
    source_embedding_overrides = parse_source_embedding_args(
        args.source_embedding_dirs, source_map
    )
    source_embedding_map = build_source_embedding_map(
        source_map, source_embedding_overrides
    )
    # Show embedding dirs (only non-default ones, or all if any override exists)
    if source_embedding_overrides:
        print("  Source embedding directories:")
        for name in sorted(source_embedding_map.keys()):
            emb_dir = source_embedding_map[name]
            is_custom = name in source_embedding_overrides
            suffix = " (custom)" if is_custom else " (default)"
            print(f"    {name} -> {emb_dir}{suffix}")

    # --- Step 2: Load and validate metadata ---
    print("Step 2: Loading and validating metadata...")
    metadata = load_and_validate_metadata(metadata_path, args.origin_column, source_map)
    n_participants = metadata["participant_label"].nunique()
    n_specimens = metadata["specimen_label"].nunique()
    print(f"  {n_participants} participants, {n_specimens} specimens")

    # --- Step 3: Build participant -> source mapping ---
    print("Step 3: Building participant-to-source mapping...")
    participant_source_map = build_participant_source_map(
        metadata, args.origin_column, source_map
    )
    participant_embedding_map = build_participant_embedding_map(
        metadata, args.origin_column, source_embedding_map
    )
    # Sanity check: every participant in metadata has a source
    metadata_participants = set(str(p) for p in metadata["participant_label"].unique())
    mapped_participants = set(participant_source_map.keys())
    assert metadata_participants == mapped_participants, (
        f"Participant set mismatch: {len(metadata_participants)} in metadata vs "
        f"{len(mapped_participants)} in source map"
    )
    assert set(participant_embedding_map.keys()) == mapped_participants, (
        f"Participant embedding map mismatch: "
        f"{len(participant_embedding_map)} vs {len(mapped_participants)} in source map"
    )

    # Per-source counts (reverse-lookup: source path -> origin name)
    path_to_origin = {path: name for name, path in source_map.items()}
    source_counts = {}
    for label, source_dir in participant_source_map.items():
        origin_name = path_to_origin[source_dir]
        source_counts[origin_name] = source_counts.get(origin_name, 0) + 1
    for name, count in sorted(source_counts.items()):
        print(f"  {name}: {count} participants")

    # --- Step 4: Validate source files exist ---
    print("Step 4: Validating source cache files...")
    missing = validate_source_files(participant_source_map, participant_embedding_map)
    if missing:
        print(
            f"Error: {len(missing)} required file(s) missing from source caches:",
            file=sys.stderr,
        )
        for m in missing[:30]:
            print(m, file=sys.stderr)
        if len(missing) > 30:
            print(f"  ... and {len(missing) - 30} more", file=sys.stderr)
        sys.exit(1)
    n_files_per_participant = len(PARTICIPANT_FILE_PATTERNS) + len(EMBEDDING_FILE_PATTERNS)
    n_expected = n_participants * n_files_per_participant
    print(f"  All {n_expected} required files found across source caches.")

    # --- Step 5: Prepare output directory ---
    print(f"Step 5: Preparing output directory: {output_cache_dir}")
    embedding_is_external = (output_embedding_dir != output_cache_dir / "embeddings")
    if embedding_is_external:
        print(f"  Output embeddings: {output_embedding_dir}")

    # Check output dirs aren't nested inside each other.
    # --overwrite deletes both output_cache_dir artifacts and output_embedding_dir
    # via rmtree. If one is a parent of the other, rmtree on the parent destroys both.
    if embedding_is_external:
        try:
            output_cache_dir.relative_to(output_embedding_dir)
            print(
                f"Error: output cache directory is inside the output embedding directory:\n"
                f"  Output cache dir:      {output_cache_dir}\n"
                f"  Output embedding dir:  {output_embedding_dir}\n"
                f"  --overwrite would destroy both. Use non-nested directory trees.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass
        try:
            output_embedding_dir.relative_to(output_cache_dir)
            print(
                f"Error: output embedding directory is inside the output cache directory:\n"
                f"  Output embedding dir:  {output_embedding_dir}\n"
                f"  Output cache dir:      {output_cache_dir}\n"
                f"  --overwrite would destroy both. Use non-nested directory trees.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass

    # Validate output doesn't point to any source before any side effects
    for name, source_dir in source_map.items():
        if output_cache_dir == source_dir:
            print(
                f"Error: output directory is the same as source '{name}': {source_dir}",
                file=sys.stderr,
            )
            sys.exit(1)

    # Validate output embedding dir doesn't overlap with any source embedding dir
    for name, src_emb_dir in source_embedding_map.items():
        if output_embedding_dir == src_emb_dir:
            print(
                f"Error: output embedding directory is the same as source '{name}' "
                f"embedding directory: {src_emb_dir}\n"
                f"  This would copy files onto themselves. Use a different "
                f"--output-embedding-dir.",
                file=sys.stderr,
            )
            sys.exit(1)

    # Check for dangerous nesting (source inside output).
    # --overwrite deletes output_cache_dir contents recursively; if a source
    # directory is nested inside it, --overwrite would destroy source data.
    for name, source_dir in source_map.items():
        try:
            source_dir.relative_to(output_cache_dir)
            print(
                f"Error: source '{name}' is inside the output cache directory:\n"
                f"  source: {source_dir}\n"
                f"  output: {output_cache_dir}\n"
                f"  --overwrite would destroy source data. "
                f"Use separate, non-nested directory trees.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass
    for name, src_emb_dir in source_embedding_map.items():
        try:
            src_emb_dir.relative_to(output_cache_dir)
            print(
                f"Error: source '{name}' embedding directory is inside the output "
                f"cache directory:\n"
                f"  source embeddings: {src_emb_dir}\n"
                f"  output cache:      {output_cache_dir}\n"
                f"  --overwrite would destroy source embeddings. "
                f"Use separate, non-nested directory trees.",
                file=sys.stderr,
            )
            sys.exit(1)
        except ValueError:
            pass

    # --overwrite also deletes external output_embedding_dir; check sources aren't inside it
    if embedding_is_external:
        for name, source_dir in source_map.items():
            try:
                source_dir.relative_to(output_embedding_dir)
                print(
                    f"Error: source '{name}' is inside the output embedding directory:\n"
                    f"  source: {source_dir}\n"
                    f"  output embeddings: {output_embedding_dir}\n"
                    f"  --overwrite would destroy source data. "
                    f"Use separate, non-nested directory trees.",
                    file=sys.stderr,
                )
                sys.exit(1)
            except ValueError:
                pass
        for name, src_emb_dir in source_embedding_map.items():
            try:
                src_emb_dir.relative_to(output_embedding_dir)
                print(
                    f"Error: source '{name}' embedding directory is inside the output "
                    f"embedding directory:\n"
                    f"  source embeddings: {src_emb_dir}\n"
                    f"  output embeddings: {output_embedding_dir}\n"
                    f"  --overwrite would destroy source embeddings. "
                    f"Use separate, non-nested directory trees.",
                    file=sys.stderr,
                )
                sys.exit(1)
            except ValueError:
                pass

    output_cache_dir.mkdir(parents=True, exist_ok=True)
    handle_existing_artifacts(output_cache_dir, output_embedding_dir, args.overwrite)

    # --- Step 6: Copy/link files ---
    action = "Symlinking" if args.symlink else "Copying"
    print(f"Step 6: {action} files...")
    result = copy_or_link_files(
        participant_source_map,
        participant_embedding_map,
        output_cache_dir,
        output_embedding_dir,
        args.symlink,
    )
    n_expected_files = n_participants * n_files_per_participant
    assert result["n_files"] == n_expected_files, (
        f"File count mismatch: copied {result['n_files']} but expected "
        f"{n_expected_files} ({n_participants} participants x "
        f"{n_files_per_participant} files)"
    )
    print(
        f"  {result['n_files']} files {'linked' if args.symlink else 'copied'} "
        f"for {result['n_participants']} participants "
        f"({format_size(result['total_bytes'])})"
    )

    # --- Step 7: Save metadata as TSV ---
    print("Step 7: Saving metadata...")
    save_metadata_tsv(metadata, output_cache_dir)
    print("  Saved metadata.tsv and metadata_processed.tsv")

    # --- Step 8: Validate output ---
    print("Step 8: Validating output cache...")
    errors = validate_output(
        participant_source_map, output_cache_dir, output_embedding_dir, args.symlink
    )
    if errors:
        print(f"\nValidation FAILED -- {len(errors)} issue(s):", file=sys.stderr)
        for e in errors[:20]:
            print(f"  - {e}", file=sys.stderr)
        if len(errors) > 20:
            print(f"  ... and {len(errors) - 20} more", file=sys.stderr)
        sys.exit(1)
    print("  All files validated successfully.")

    # --- Step 9: Summary ---
    print_summary(metadata, args.origin_column, source_map)

    print(f"{'=' * 65}")
    print(f"  Merged cache created successfully.")
    print(f"{'=' * 65}")
    print(f"  Output:    {output_cache_dir}")
    if embedding_is_external:
        print(f"  Embeddings: {output_embedding_dir}")
    print(f"  Mode:      {'symlinks' if args.symlink else 'copies'}")
    print()
    print("  To train on this merged cache:")
    print(f"    python malid_lite/training/train_ensemble.py \\")
    print(f"        --metadata-path {output_cache_dir / 'metadata_processed.tsv'} \\")
    print(f"        --cache-dir {output_cache_dir} \\")
    if embedding_is_external:
        print(f"        --model3-embedding-dir {output_embedding_dir} \\")
    print(f"        --dataset-name <your-dataset-name> \\")
    print(f"        --classification-mode multiclass")
    print()


if __name__ == "__main__":
    main()
