#!/usr/bin/env python
"""Merge participant and embedding cache files from two separate source caches into one.

This script builds a unified Mal-ID-Lite cache by copying (or symlinking) per-participant
cache files from two independent source caches into a single output cache directory.
The result is a cache that the pipeline can use directly for training (train_ensemble.py)
without rebuilding participant caches or recomputing embeddings.

The script determines which source cache to use for each participant by reading a
"data-origin" column (or any user-specified column) from the metadata file. Each unique
value in that column is mapped to a source cache directory via --source arguments.

What gets created in the output directory:
  - participants/{label}_clean.parquet       (Stage 1 preprocessed sequences)
  - participants/{label}_stats.json          (preprocessing statistics)
  - embeddings/{label}_embeddings.npy        (ESM-2 sequence embeddings)
  - embeddings/{label}_downsampled.parquet   (downsampled sequences matching embeddings)
  - embeddings/{label}_stats.json            (embedding statistics)
  - metadata.tsv                             (tab-separated metadata for the loader)
  - metadata_processed.tsv                   (same content -- loader uses this on subsequent runs)

What is NOT created (auto-generated by the pipeline at training time):
  - data_folds/    (fold-level sequence data)
  - splits/        (train/test split definitions)
  - reports/       (data quality reports)

Arguments
---------
--metadata PATH  (required)
    Path to the united metadata file (CSV or TSV). Must contain columns:
    participant_label, specimen_label, disease, CV_fold (or legacy name
    malid_cross_validation_fold_id_when_in_test_set), and the origin column
    (see --origin-column). Separator is auto-detected from file extension:
    .csv -> comma, .tsv -> tab.

--origin-column NAME  (required)
    Name of the metadata column that identifies which source cache a
    participant belongs to. Each unique value in this column must have a
    corresponding --source argument.

--source NAME=PATH  (required, repeatable)
    Maps a value from the origin column to a source cache directory.
    Format: VALUE=PATH where VALUE is one of the unique values in the
    origin column and PATH is the directory containing participants/ and
    embeddings/ subdirectories. Must provide exactly one --source for each
    unique value in the origin column.

    Example:
        --source external-dataset=/path/to/T1D_external_only
        --source mal-id-dataset=/path/to/mal-id-orig-data

--output-cache-dir PATH  (required)
    Output directory for the merged cache. The script creates participants/
    and embeddings/ subdirectories here, along with metadata.tsv and
    metadata_processed.tsv.

--symlink  (optional, default: off)
    Create symbolic links to source files instead of copying them. Much
    faster and saves disk space, but the merged cache becomes dependent on
    the source caches remaining in place and unchanged.

--overwrite  (optional, default: off)
    If cache artifacts already exist in the output directory (participants/,
    embeddings/, metadata.tsv, metadata_processed.tsv), delete them before
    writing. Without this flag, the script errors if any of these exist.
    The input metadata file is never deleted, even if it resides in the
    output directory.

Usage
-----
    # Basic usage with two source caches:
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united

    # With symlinks (saves disk space, faster):
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united \\
        --symlink

    # Overwrite previous merge:
    python scripts/cache_tools/merge_caches.py \\
        --metadata /path/to/metadata_united.csv \\
        --origin-column data-origin \\
        --source external-dataset=/path/to/T1D_external_only \\
        --source mal-id-dataset=/path/to/mal-id-orig-data \\
        --output-cache-dir /path/to/T1D_united \\
        --overwrite

    # After creating the merged cache, train with:
    python malid_lite/training/train_ensemble.py \\
        --metadata-path /path/to/T1D_united/metadata_processed.tsv \\
        --cache-dir /path/to/T1D_united \\
        --dataset-name T1D_united \\
        --classification-mode multiclass
"""

import argparse
import os
import shutil
import sys
import tempfile
from pathlib import Path

import pandas as pd

FOLD_COL = "CV_fold"
_LEGACY_FOLD_COL = "malid_cross_validation_fold_id_when_in_test_set"

REQUIRED_METADATA_COLS = [
    "participant_label",
    "specimen_label",
    "disease",
    FOLD_COL,
]

# Per-participant files that must exist in each source cache
PARTICIPANT_CACHE_FILES = [
    "participants/{label}_clean.parquet",
    "participants/{label}_stats.json",
]
EMBEDDING_CACHE_FILES = [
    "embeddings/{label}_embeddings.npy",
    "embeddings/{label}_downsampled.parquet",
    "embeddings/{label}_stats.json",
]
ALL_REQUIRED_FILES = PARTICIPANT_CACHE_FILES + EMBEDDING_CACHE_FILES

# Artifacts the script writes into the output directory.
# --overwrite deletes exactly these (not the whole directory).
OUTPUT_ARTIFACTS = ["participants", "embeddings", "metadata.tsv", "metadata_processed.tsv"]


def parse_args():
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Merge participant and embedding cache files from two separate source "
            "caches into a single unified cache for Mal-ID-Lite training."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python scripts/cache_tools/merge_caches.py \\\n"
            "      --metadata data/metadata_united.csv \\\n"
            "      --origin-column data-origin \\\n"
            "      --source external-dataset=/path/to/cache_a \\\n"
            "      --source mal-id-dataset=/path/to/cache_b \\\n"
            "      --output-cache-dir /path/to/merged_cache\n\n"
            "  # With symlinks:\n"
            "  python scripts/cache_tools/merge_caches.py \\\n"
            "      --metadata data/metadata_united.csv \\\n"
            "      --origin-column data-origin \\\n"
            "      --source external-dataset=/path/to/cache_a \\\n"
            "      --source mal-id-dataset=/path/to/cache_b \\\n"
            "      --output-cache-dir /path/to/merged_cache \\\n"
            "      --symlink\n"
        ),
    )

    parser.add_argument(
        "--metadata",
        type=Path,
        required=True,
        help="Path to the united metadata file (CSV or TSV, auto-detected from extension).",
    )
    parser.add_argument(
        "--origin-column",
        type=str,
        required=True,
        help=(
            "Metadata column that identifies which source cache each participant "
            "belongs to. Each unique value must have a corresponding --source."
        ),
    )
    parser.add_argument(
        "--source",
        type=str,
        action="append",
        required=True,
        dest="sources",
        metavar="NAME=PATH",
        help=(
            "Map an origin-column value to a source cache directory. "
            "Format: VALUE=PATH. Repeatable — provide one per unique origin value."
        ),
    )
    parser.add_argument(
        "--output-cache-dir",
        type=Path,
        required=True,
        help="Output directory for the merged cache.",
    )
    parser.add_argument(
        "--symlink",
        action="store_true",
        help="Create symbolic links instead of copying files.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help=(
            "Delete existing cache artifacts in the output directory before writing. "
            "Only removes participants/, embeddings/, metadata.tsv, metadata_processed.tsv."
        ),
    )

    return parser.parse_args()


def parse_source_args(source_args):
    """Parse --source NAME=PATH arguments into a dict.

    Parameters
    ----------
    source_args : list[str]
        Raw --source argument values, each in "NAME=PATH" format.

    Returns
    -------
    dict[str, Path]
        Mapping from origin value to source cache directory path.
    """
    source_map = {}
    for arg in source_args:
        if "=" not in arg:
            print(
                f"Error: --source argument must be in NAME=PATH format, got: '{arg}'",
                file=sys.stderr,
            )
            sys.exit(1)

        # Split on first '=' only (paths may contain '=' in theory)
        name, path_str = arg.split("=", 1)
        name = name.strip()
        path_str = path_str.strip()

        if not name:
            print(f"Error: empty name in --source argument: '{arg}'", file=sys.stderr)
            sys.exit(1)
        if not path_str:
            print(f"Error: empty path in --source argument: '{arg}'", file=sys.stderr)
            sys.exit(1)

        if name in source_map:
            print(
                f"Error: duplicate --source name '{name}'. "
                f"Each origin value should appear exactly once.",
                file=sys.stderr,
            )
            sys.exit(1)

        source_path = Path(path_str).resolve()
        if not source_path.is_dir():
            print(
                f"Error: source cache directory does not exist: {source_path}\n"
                f"  (from --source {name}={path_str})",
                file=sys.stderr,
            )
            sys.exit(1)

        # Check for two different names pointing to the same directory
        for existing_name, existing_path in source_map.items():
            if source_path == existing_path:
                print(
                    f"Error: --source '{name}' and --source '{existing_name}' both "
                    f"point to the same directory: {source_path}",
                    file=sys.stderr,
                )
                sys.exit(1)

        source_map[name] = source_path

    return source_map


def detect_separator(metadata_path):
    """Detect CSV/TSV separator from file extension.

    Parameters
    ----------
    metadata_path : Path
        Path to the metadata file.

    Returns
    -------
    str
        ',' for .csv, '\\t' for .tsv.
    """
    ext = metadata_path.suffix.lower()
    if ext == ".csv":
        return ","
    elif ext == ".tsv":
        return "\t"
    else:
        print(
            f"Error: cannot auto-detect separator for extension '{ext}'. "
            f"Rename the metadata file to .csv or .tsv.",
            file=sys.stderr,
        )
        sys.exit(1)


def load_and_validate_metadata(metadata_path, origin_column, source_map):
    """Load metadata, validate required columns and origin-to-source mapping.

    Parameters
    ----------
    metadata_path : Path
        Path to the metadata file.
    origin_column : str
        Column name that identifies which source cache each participant belongs to.
    source_map : dict[str, Path]
        Mapping from origin-column values to source cache directories.

    Returns
    -------
    pd.DataFrame
        Validated metadata with CV_fold column (legacy name normalized).
    """
    if not metadata_path.is_file():
        print(f"Error: metadata file not found: {metadata_path}", file=sys.stderr)
        sys.exit(1)

    sep = detect_separator(metadata_path)
    metadata = pd.read_csv(metadata_path, sep=sep)

    if metadata.empty:
        print(f"Error: metadata file has no data rows: {metadata_path}", file=sys.stderr)
        sys.exit(1)

    # Normalize legacy fold column name
    if _LEGACY_FOLD_COL in metadata.columns and FOLD_COL not in metadata.columns:
        metadata = metadata.rename(columns={_LEGACY_FOLD_COL: FOLD_COL})

    # Check required columns
    missing_cols = [c for c in REQUIRED_METADATA_COLS if c not in metadata.columns]
    if missing_cols:
        print(
            f"Error: metadata is missing required columns: {missing_cols}\n"
            f"  Required: {REQUIRED_METADATA_COLS}\n"
            f"  Found: {list(metadata.columns)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check origin column exists
    if origin_column not in metadata.columns:
        print(
            f"Error: origin column '{origin_column}' not found in metadata.\n"
            f"  Available columns: {list(metadata.columns)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check for NaN in critical columns
    for col in ["participant_label", "specimen_label", "disease", FOLD_COL, origin_column]:
        n_nan = metadata[col].isna().sum()
        if n_nan > 0:
            print(
                f"Error: metadata has {n_nan} NaN value(s) in column '{col}'.",
                file=sys.stderr,
            )
            sys.exit(1)

    # Validate origin column values match --source arguments exactly
    origin_values = set(metadata[origin_column].unique())
    source_names = set(source_map.keys())

    missing_sources = origin_values - source_names
    if missing_sources:
        print(
            f"Error: origin column '{origin_column}' has values with no --source mapping:\n"
            f"  Missing: {sorted(missing_sources)}\n"
            f"  Provided --source names: {sorted(source_names)}",
            file=sys.stderr,
        )
        sys.exit(1)

    unused_sources = source_names - origin_values
    if unused_sources:
        print(
            f"Error: --source name(s) not found in origin column '{origin_column}':\n"
            f"  Unused: {sorted(unused_sources)}\n"
            f"  Origin values in metadata: {sorted(origin_values)}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check for duplicate specimen labels
    if metadata["specimen_label"].duplicated().any():
        dupes = metadata["specimen_label"][metadata["specimen_label"].duplicated()].tolist()
        print(
            f"Error: metadata has duplicate specimen_labels: {dupes[:10]}",
            file=sys.stderr,
        )
        sys.exit(1)

    # Check that each participant maps to exactly one origin
    participant_origins = metadata.groupby("participant_label")[origin_column].nunique()
    multi_origin = participant_origins[participant_origins > 1]
    if len(multi_origin) > 0:
        print(
            f"Error: {len(multi_origin)} participant(s) appear in multiple origins:\n"
            f"  {multi_origin.index.tolist()[:10]}",
            file=sys.stderr,
        )
        sys.exit(1)

    return metadata


def build_participant_source_map(metadata, origin_column, source_map):
    """Build a mapping from each participant label to its source cache directory.

    Parameters
    ----------
    metadata : pd.DataFrame
        Validated metadata.
    origin_column : str
        Column identifying the source.
    source_map : dict[str, Path]
        Origin value -> source cache directory.

    Returns
    -------
    dict[str, Path]
        participant_label -> source cache directory.
    """
    # One row per participant (take first row for multi-specimen participants)
    participant_origin = (
        metadata.drop_duplicates(subset="participant_label")
        .set_index("participant_label")[origin_column]
    )
    return {
        str(label): source_map[origin]
        for label, origin in participant_origin.items()
    }


def validate_source_files(participant_source_map):
    """Verify all required cache files exist in the source caches.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        participant_label -> source cache directory.

    Returns
    -------
    list[str]
        List of error messages (empty if all files found).
    """
    missing = []
    for label, source_dir in participant_source_map.items():
        for pattern in ALL_REQUIRED_FILES:
            file_path = source_dir / pattern.format(label=label)
            if not file_path.exists():
                missing.append(
                    f"  {pattern.format(label=label)}  (source: {source_dir.name})"
                )

    return missing


def handle_existing_artifacts(output_cache_dir, overwrite):
    """Check for existing artifacts and handle according to --overwrite flag.

    Parameters
    ----------
    output_cache_dir : Path
        Output cache directory.
    overwrite : bool
        If True, delete existing artifacts. If False, error on conflict.
    """
    existing = []
    for name in OUTPUT_ARTIFACTS:
        path = output_cache_dir / name
        if path.exists():
            existing.append(name)

    if not existing:
        return

    if not overwrite:
        print(
            f"Error: output directory already contains cache artifacts:\n"
            + "\n".join(f"  - {name}" for name in existing)
            + "\n\n  Use --overwrite to delete them and recreate.",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"  --overwrite: removing existing artifacts...")
    for name in existing:
        path = output_cache_dir / name
        if path.is_dir():
            shutil.rmtree(path)
            print(f"    Removed directory: {name}/")
        else:
            path.unlink()
            print(f"    Removed file: {name}")


def copy_or_link_files(participant_source_map, output_cache_dir, use_symlinks):
    """Copy (or symlink) all participant and embedding files to the output cache.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        participant_label -> source cache directory.
    output_cache_dir : Path
        Destination cache directory.
    use_symlinks : bool
        If True, create symbolic links instead of copies.

    Returns
    -------
    dict
        Summary: n_files, total_bytes, n_participants.
    """
    participants_dir = output_cache_dir / "participants"
    embeddings_dir = output_cache_dir / "embeddings"
    participants_dir.mkdir(parents=True, exist_ok=True)
    embeddings_dir.mkdir(parents=True, exist_ok=True)

    n_files = 0
    total_bytes = 0
    action = "Linking" if use_symlinks else "Copying"

    sorted_participants = sorted(participant_source_map.keys())
    n_total = len(sorted_participants)

    for idx, label in enumerate(sorted_participants, 1):
        if idx == 1 or idx == n_total or idx % 50 == 0:
            print(f"  {action} {idx}/{n_total}: {label}")

        source_dir = participant_source_map[label]

        for pattern in ALL_REQUIRED_FILES:
            src = source_dir / pattern.format(label=label)
            dst = output_cache_dir / pattern.format(label=label)

            if use_symlinks:
                dst.symlink_to(src.resolve())
            else:
                shutil.copy2(src, dst)

            n_files += 1
            total_bytes += src.stat().st_size

    return {
        "n_files": n_files,
        "total_bytes": total_bytes,
        "n_participants": n_total,
    }


def save_metadata_tsv(metadata, output_cache_dir):
    """Save metadata as metadata.tsv and metadata_processed.tsv (tab-separated).

    Uses atomic writes (write to temp file, then rename) to prevent corruption.

    Parameters
    ----------
    metadata : pd.DataFrame
        The united metadata to save.
    output_cache_dir : Path
        Destination cache directory.
    """
    for filename in ("metadata.tsv", "metadata_processed.tsv"):
        target = output_cache_dir / filename
        fd, tmp_path = tempfile.mkstemp(dir=output_cache_dir, suffix=".tsv")
        try:
            os.close(fd)
            metadata.to_csv(tmp_path, sep="\t", index=False)
            os.rename(tmp_path, target)
        except Exception:
            if Path(tmp_path).exists():
                os.unlink(tmp_path)
            raise


def validate_output(participant_source_map, output_cache_dir, use_symlinks):
    """Validate that all expected files exist in the output cache.

    Parameters
    ----------
    participant_source_map : dict[str, Path]
        Expected participant labels and their sources.
    output_cache_dir : Path
        Output cache directory to validate.
    use_symlinks : bool
        If True, also verify symlinks are not broken.

    Returns
    -------
    list[str]
        List of error messages (empty if all valid).
    """
    errors = []

    # Check metadata files
    for filename in ("metadata.tsv", "metadata_processed.tsv"):
        path = output_cache_dir / filename
        if not path.exists():
            errors.append(f"Missing: {filename}")
        elif path.stat().st_size == 0:
            errors.append(f"Empty: {filename}")

    # Check per-participant files
    for label in sorted(participant_source_map.keys()):
        for pattern in ALL_REQUIRED_FILES:
            rel_path = pattern.format(label=label)
            file_path = output_cache_dir / rel_path
            if not file_path.exists():
                errors.append(f"Missing: {rel_path}")
            else:
                # For symlinks, verify the target exists
                if use_symlinks and file_path.is_symlink():
                    if not file_path.resolve().exists():
                        errors.append(f"Broken symlink: {rel_path}")
                        continue
                # Check file is non-empty (stat follows symlinks)
                if file_path.stat().st_size == 0:
                    errors.append(f"Empty file: {rel_path}")

    return errors


def format_size(bytes_size):
    """Format bytes to human-readable size string."""
    for unit in ["B", "KB", "MB", "GB"]:
        if bytes_size < 1024:
            return f"{bytes_size:.1f} {unit}"
        bytes_size /= 1024
    return f"{bytes_size:.1f} TB"


def print_summary(metadata, origin_column, source_map):
    """Print a summary of the merged cache contents.

    Parameters
    ----------
    metadata : pd.DataFrame
        The united metadata.
    origin_column : str
        Column identifying the source.
    source_map : dict[str, Path]
        Origin value -> source cache directory.
    """
    participants_df = metadata.drop_duplicates(subset="participant_label")
    diseases = sorted(metadata["disease"].unique())
    folds = sorted(int(f) for f in metadata[FOLD_COL].unique())

    print(f"\n{'=' * 65}")
    print("  MERGED CACHE SUMMARY")
    print(f"{'=' * 65}")
    print(f"  Participants: {len(participants_df)}")
    print(f"  Specimens:    {metadata['specimen_label'].nunique()}")
    print(f"  Diseases:     {len(diseases)} -- {diseases}")
    print(f"  Folds:        {len(folds)} -- {folds}")

    # Per-source breakdown
    print(f"\n  Per source:")
    for origin_value in sorted(source_map.keys()):
        origin_mask = metadata[origin_column] == origin_value
        origin_participants = metadata.loc[origin_mask, "participant_label"].nunique()
        origin_specimens = origin_mask.sum()
        print(
            f"    {origin_value}: "
            f"{origin_participants} participants, {origin_specimens} specimens "
            f"(from {source_map[origin_value]})"
        )

    # Per-fold, per-disease breakdown
    print(f"\n  {'Fold':<6} {'Participants':<14} ", end="")
    for d in diseases:
        label = d[:18] if len(d) > 18 else d
        print(f"{label:<20} ", end="")
    print()
    print(f"  {'-' * 6} {'-' * 14} ", end="")
    for _ in diseases:
        print(f"{'-' * 20} ", end="")
    print()

    for fold_id in folds:
        fold_parts = participants_df[participants_df[FOLD_COL] == fold_id]
        print(f"  {fold_id:<6} {len(fold_parts):<14} ", end="")
        for d in diseases:
            n = (fold_parts["disease"] == d).sum()
            print(f"{n:<20} ", end="")
        print()

    print(f"  {'-' * 6} {'-' * 14} ", end="")
    for _ in diseases:
        print(f"{'-' * 20} ", end="")
    print()
    print(f"  {'Total':<6} {len(participants_df):<14} ", end="")
    for d in diseases:
        n = (participants_df["disease"] == d).sum()
        print(f"{n:<20} ", end="")
    print()
    print()


def main():
    args = parse_args()

    metadata_path = args.metadata.resolve()
    output_cache_dir = args.output_cache_dir.resolve()

    # --- Step 1: Parse --source arguments ---
    print("Step 1: Parsing source arguments...")
    source_map = parse_source_args(args.sources)
    for name, path in sorted(source_map.items()):
        print(f"  {name} -> {path}")

    # --- Step 2: Load and validate metadata ---
    print("Step 2: Loading and validating metadata...")
    metadata = load_and_validate_metadata(metadata_path, args.origin_column, source_map)
    n_participants = metadata["participant_label"].nunique()
    n_specimens = metadata["specimen_label"].nunique()
    print(f"  {n_participants} participants, {n_specimens} specimens")

    # --- Step 3: Build participant -> source mapping ---
    print("Step 3: Building participant-to-source mapping...")
    participant_source_map = build_participant_source_map(
        metadata, args.origin_column, source_map
    )
    # Sanity check: every participant in metadata has a source
    metadata_participants = set(str(p) for p in metadata["participant_label"].unique())
    mapped_participants = set(participant_source_map.keys())
    assert metadata_participants == mapped_participants, (
        f"Participant set mismatch: {len(metadata_participants)} in metadata vs "
        f"{len(mapped_participants)} in source map"
    )

    # Per-source counts (reverse-lookup: source path -> origin name)
    path_to_origin = {path: name for name, path in source_map.items()}
    source_counts = {}
    for label, source_dir in participant_source_map.items():
        origin_name = path_to_origin[source_dir]
        source_counts[origin_name] = source_counts.get(origin_name, 0) + 1
    for name, count in sorted(source_counts.items()):
        print(f"  {name}: {count} participants")

    # --- Step 4: Validate source files exist ---
    print("Step 4: Validating source cache files...")
    missing = validate_source_files(participant_source_map)
    if missing:
        print(
            f"Error: {len(missing)} required file(s) missing from source caches:",
            file=sys.stderr,
        )
        for m in missing[:30]:
            print(m, file=sys.stderr)
        if len(missing) > 30:
            print(f"  ... and {len(missing) - 30} more", file=sys.stderr)
        sys.exit(1)
    n_expected = n_participants * len(ALL_REQUIRED_FILES)
    print(f"  All {n_expected} required files found across source caches.")

    # --- Step 5: Prepare output directory ---
    print(f"Step 5: Preparing output directory: {output_cache_dir}")

    # Validate output doesn't point to any source before any side effects
    for name, source_dir in source_map.items():
        if output_cache_dir == source_dir:
            print(
                f"Error: output directory is the same as source '{name}': {source_dir}",
                file=sys.stderr,
            )
            sys.exit(1)

    output_cache_dir.mkdir(parents=True, exist_ok=True)
    handle_existing_artifacts(output_cache_dir, args.overwrite)

    # --- Step 6: Copy/link files ---
    action = "Symlinking" if args.symlink else "Copying"
    print(f"Step 6: {action} files...")
    result = copy_or_link_files(participant_source_map, output_cache_dir, args.symlink)
    n_expected_files = n_participants * len(ALL_REQUIRED_FILES)
    assert result["n_files"] == n_expected_files, (
        f"File count mismatch: copied {result['n_files']} but expected "
        f"{n_expected_files} ({n_participants} participants x {len(ALL_REQUIRED_FILES)} files)"
    )
    print(
        f"  {result['n_files']} files {'linked' if args.symlink else 'copied'} "
        f"for {result['n_participants']} participants "
        f"({format_size(result['total_bytes'])})"
    )

    # --- Step 7: Save metadata as TSV ---
    print("Step 7: Saving metadata...")
    save_metadata_tsv(metadata, output_cache_dir)
    print("  Saved metadata.tsv and metadata_processed.tsv")

    # --- Step 8: Validate output ---
    print("Step 8: Validating output cache...")
    errors = validate_output(participant_source_map, output_cache_dir, args.symlink)
    if errors:
        print(f"\nValidation FAILED -- {len(errors)} issue(s):", file=sys.stderr)
        for e in errors[:20]:
            print(f"  - {e}", file=sys.stderr)
        if len(errors) > 20:
            print(f"  ... and {len(errors) - 20} more", file=sys.stderr)
        sys.exit(1)
    print("  All files validated successfully.")

    # --- Step 9: Summary ---
    print_summary(metadata, args.origin_column, source_map)

    print(f"{'=' * 65}")
    print(f"  Merged cache created successfully.")
    print(f"{'=' * 65}")
    print(f"  Output:    {output_cache_dir}")
    print(f"  Mode:      {'symlinks' if args.symlink else 'copies'}")
    print()
    print("  To train on this merged cache:")
    print(f"    python malid_lite/training/train_ensemble.py \\")
    print(f"        --metadata-path {output_cache_dir / 'metadata_processed.tsv'} \\")
    print(f"        --cache-dir {output_cache_dir} \\")
    print(f"        --dataset-name <your-dataset-name> \\")
    print(f"        --classification-mode multiclass")
    print()


if __name__ == "__main__":
    main()
